import { BankTransaction, MccPolicyMaster } from "./corporate-card-types";

export const mockMccPolicies: MccPolicyMaster[] = [
  { mcc_code: "P001", description: "Holiday Inn", category: "Entertainment", mcc_code_ref: "5812", mcc_code_description: "Eating Places/Restaurants", description_subtype: "Client Meal — HoReCa / Business Visit", policy_type: "AUTO_APPROVE", threshold_amount: 3000, currency: "THB", active_flag: true, updated_at: "2026-02-20T10:00:00Z" },
  { mcc_code: "P002", description: "Trainer/Guest Entertainment", category: "Entertainment", mcc_code_ref: "5812", mcc_code_description: "Eating Places/Restaurants", description_subtype: "Trainer / Guest Entertainment (ค่าเลี้ยงวิทยากร/แขก)", policy_type: "AUTO_APPROVE", threshold_amount: 2000, currency: "THB", active_flag: true, updated_at: "2026-02-18T08:30:00Z" },
  { mcc_code: "P003", description: "Entertainment >3000", category: "Entertainment", mcc_code_ref: "5812", mcc_code_description: "Eating Places/Restaurants", description_subtype: "Entertainment >3,000 THB (ต้องอนุมัติ)", policy_type: "REQUIRES_APPROVAL", threshold_amount: null, currency: "THB", active_flag: true, updated_at: "2026-02-15T14:00:00Z" },
  { mcc_code: "P004", description: "Motion Picture", category: "Entertainment", mcc_code_ref: "7832", mcc_code_description: "Motion Picture Theaters", description_subtype: "Motion Picture / Non-Business Entertainment", policy_type: "AUTO_REJECT", threshold_amount: null, currency: "THB", active_flag: false, updated_at: "2026-01-30T10:00:00Z" },
  { mcc_code: "P005", description: "Hotel Domestic Standard", category: "Hotel", mcc_code_ref: "7011", mcc_code_description: "Hotels/Motels/Resorts", description_subtype: "Hotel — Domestic Standard Rate (ระดับ ASGM–Division Mgr)", policy_type: "AUTO_APPROVE", threshold_amount: 2000, currency: "THB", active_flag: true, updated_at: "2026-02-14T16:00:00Z" },
  { mcc_code: "P006", description: "Hotel Domestic SGM", category: "Hotel", mcc_code_ref: "7011", mcc_code_description: "Hotels/Motels/Resorts", description_subtype: "Hotel — Domestic SGM/Senior Mgr (พักคู่)", policy_type: "AUTO_APPROVE", threshold_amount: 2500, currency: "THB", active_flag: true, updated_at: "2026-02-14T16:00:00Z" },
  { mcc_code: "P007", description: "Hotel Domestic AD-Chief", category: "Hotel", mcc_code_ref: "7011", mcc_code_description: "Hotels/Motels/Resorts", description_subtype: "Hotel — Domestic Associate Director–Chief (พักเดี่ยว)", policy_type: "AUTO_APPROVE", threshold_amount: 4000, currency: "THB", active_flag: true, updated_at: "2026-02-14T16:00:00Z" },
  { mcc_code: "P008", description: "Hotel Domestic GCEO", category: "Hotel", mcc_code_ref: "7011", mcc_code_description: "Hotels/Motels/Resorts", description_subtype: "Hotel — Domestic GCEO/CEO BU (พักเดี่ยว)", policy_type: "AUTO_APPROVE", threshold_amount: 5000, currency: "THB", active_flag: true, updated_at: "2026-02-14T16:00:00Z" },
  { mcc_code: "P009", description: "Hotel Domestic Special Area", category: "Hotel", mcc_code_ref: "7011", mcc_code_description: "Hotels/Motels/Resorts", description_subtype: "Hotel — Domestic Special Area (พื้นที่พิเศษ: เกาะ/Event ขนาดใหญ่)", policy_type: "AUTO_APPROVE", threshold_amount: 3500, currency: "THB", active_flag: true, updated_at: "2026-02-14T16:00:00Z" },
  { mcc_code: "P010", description: "Hotel Intl Group A&B Senior", category: "Hotel", mcc_code_ref: "3501", mcc_code_description: "Holiday Inn", description_subtype: "Hotel — International Group A & B (Senior Dir/Chief Level)", policy_type: "AUTO_APPROVE", threshold_amount: 7500, currency: "THB", active_flag: true, updated_at: "2026-02-20T10:00:00Z" },
  { mcc_code: "P011", description: "Hotel Intl Group A&B Assoc", category: "Hotel", mcc_code_ref: "3501", mcc_code_description: "Holiday Inn", description_subtype: "Hotel — International Group A & B (Assoc Dir–Director)", policy_type: "AUTO_APPROVE", threshold_amount: 6000, currency: "THB", active_flag: true, updated_at: "2026-02-20T10:00:00Z" },
  { mcc_code: "P012", description: "Hotel Intl Group A&B SrMgr", category: "Hotel", mcc_code_ref: "3501", mcc_code_description: "Holiday Inn", description_subtype: "Hotel — International Group A & B (Sr.Mgr/SGM/Area Mgr)", policy_type: "AUTO_APPROVE", threshold_amount: 6000, currency: "THB", active_flag: true, updated_at: "2026-02-20T10:00:00Z" },
  { mcc_code: "P013", description: "Hotel Intl Group C", category: "Hotel", mcc_code_ref: "3501", mcc_code_description: "Holiday Inn", description_subtype: "Hotel — International Group C (ASEAN & Others)", policy_type: "AUTO_APPROVE", threshold_amount: 4500, currency: "THB", active_flag: true, updated_at: "2026-02-20T10:00:00Z" },
  { mcc_code: "P014", description: "Meals Per Diem Domestic", category: "Meals & Entertainment", mcc_code_ref: "5812", mcc_code_description: "Eating Places/Restaurants", description_subtype: "Meals — Per Diem Domestic Travel (ค่าเบี้ยเลี้ยงในประเทศ)", policy_type: "AUTO_APPROVE", threshold_amount: 200, currency: "THB", active_flag: true, updated_at: "2026-02-10T09:00:00Z" },
  { mcc_code: "P015", description: "Staff Meeting", category: "Meals & Entertainment", mcc_code_ref: "5812", mcc_code_description: "Eating Places/Restaurants", description_subtype: "Meals — Staff Meeting / Stock Count (ค่าอาหารประชุม/นับสต็อค)", policy_type: "AUTO_APPROVE", threshold_amount: 3000, currency: "THB", active_flag: true, updated_at: "2026-02-10T09:00:00Z" },
  { mcc_code: "P016", description: "Night Shift", category: "Meals & Entertainment", mcc_code_ref: "5812", mcc_code_description: "Eating Places/Restaurants", description_subtype: "Meals — Night Shift Special Operation (กะดึก)", policy_type: "AUTO_APPROVE", threshold_amount: 60, currency: "THB", active_flag: true, updated_at: "2026-02-10T09:00:00Z" },
  { mcc_code: "P017", description: "Overseas Per Diem CEO", category: "Meals & Entertainment", mcc_code_ref: "5812", mcc_code_description: "Eating Places/Restaurants", description_subtype: "Meals — Overseas Per Diem Group A & B CEO/GCEO", policy_type: "AUTO_APPROVE", threshold_amount: 2400, currency: "THB", active_flag: true, updated_at: "2026-02-10T09:00:00Z" },
  { mcc_code: "P018", description: "Overseas Per Diem Senior", category: "Meals & Entertainment", mcc_code_ref: "5812", mcc_code_description: "Eating Places/Restaurants", description_subtype: "Meals — Overseas Per Diem Group A & B Senior Dir/Chief", policy_type: "AUTO_APPROVE", threshold_amount: 2100, currency: "THB", active_flag: true, updated_at: "2026-02-10T09:00:00Z" },
  { mcc_code: "P019", description: "Overseas Per Diem Assoc Dir", category: "Meals & Entertainment", mcc_code_ref: "5812", mcc_code_description: "Eating Places/Restaurants", description_subtype: "Meals — Overseas Per Diem Group A & B Assoc Dir–Director", policy_type: "AUTO_APPROVE", threshold_amount: 1800, currency: "THB", active_flag: true, updated_at: "2026-02-10T09:00:00Z" },
  { mcc_code: "P020", description: "Taxicabs", category: "Transportation", mcc_code_ref: "4121", mcc_code_description: "Taxicabs/Limousines", description_subtype: "Taxi / Ride-hailing Service", policy_type: "AUTO_APPROVE", threshold_amount: 1500, currency: "THB", active_flag: true, updated_at: "2026-02-18T08:30:00Z" },
  { mcc_code: "P021", description: "Airlines", category: "Transportation", mcc_code_ref: "4511", mcc_code_description: "Airlines/Air Carriers", description_subtype: "Airline Tickets — Domestic & International", policy_type: "REQUIRES_APPROVAL", threshold_amount: null, currency: "THB", active_flag: true, updated_at: "2026-02-22T12:00:00Z" },
  { mcc_code: "P022", description: "Service Stations", category: "Transportation", mcc_code_ref: "5541", mcc_code_description: "Service Stations", description_subtype: "Fuel / Petrol Station", policy_type: "AUTO_APPROVE", threshold_amount: 2000, currency: "THB", active_flag: true, updated_at: "2026-02-19T15:00:00Z" },
  { mcc_code: "P023", description: "Bars", category: "Meals & Entertainment", mcc_code_ref: "5813", mcc_code_description: "Bars/Cocktail Lounges", description_subtype: "Bars / Cocktail Lounges", policy_type: "AUTO_REJECT", threshold_amount: null, currency: "THB", active_flag: true, updated_at: "2026-02-12T11:00:00Z" },
  { mcc_code: "P024", description: "Jewelry", category: "Personal", mcc_code_ref: "5944", mcc_code_description: "Jewelry/Watch/Clock Stores", description_subtype: "Jewelry / Personal Shopping", policy_type: "AUTO_REJECT", threshold_amount: null, currency: "THB", active_flag: true, updated_at: "2026-02-01T09:00:00Z" },
  { mcc_code: "P025", description: "Grocery", category: "Meals & Entertainment", mcc_code_ref: "5411", mcc_code_description: "Grocery Stores/Supermarkets", description_subtype: "Grocery / Supermarket Purchase", policy_type: "REQUIRES_APPROVAL", threshold_amount: null, currency: "THB", active_flag: true, updated_at: "2026-02-15T14:00:00Z" },
];

export const mockBankTransactions: BankTransaction[] = [
  {
    id: "bt-001", file_id: "file-001", transaction_id: "TXN-2026022801",
    cardholder_employee_id: "EMP001", cardholder_name: "Somchai Jaidee",
    transaction_date: "2026-02-28", posting_date: "2026-02-28",
    billing_amount: 2500, billing_currency: "THB",
    merchant_name: "Grab Taxi", merchant_city: "Bangkok", merchant_country: "TH",
    mcc_code: "4121", mcc_description: "Taxicabs/Limousines",
    transaction_type: "PURCHASE", authorization_code: "AUTH001", reference_number: "REF-001",
    policy_result: "AUTO_APPROVED", policy_reason: "Amount 2,500 exceeds threshold 1,500 but within daily limit",
    processing_status: "PROCESSED", created_at: "2026-02-28T08:00:00Z",
  },
  {
    id: "bt-002", file_id: "file-001", transaction_id: "TXN-2026022802",
    cardholder_employee_id: "EMP002", cardholder_name: "Wanida Srisuk",
    transaction_date: "2026-02-27", posting_date: "2026-02-28",
    billing_amount: 4500, billing_currency: "THB",
    merchant_name: "Novotel Bangkok", merchant_city: "Bangkok", merchant_country: "TH",
    mcc_code: "7011", mcc_description: "Hotels/Motels/Resorts",
    transaction_type: "PURCHASE", authorization_code: "AUTH002", reference_number: "REF-002",
    policy_result: "AUTO_APPROVED", policy_reason: "Amount within hotel threshold 8,000",
    processing_status: "PROCESSED", created_at: "2026-02-28T08:00:00Z",
  },
  {
    id: "bt-003", file_id: "file-001", transaction_id: "TXN-2026022803",
    cardholder_employee_id: "EMP001", cardholder_name: "Somchai Jaidee",
    transaction_date: "2026-02-26", posting_date: "2026-02-27",
    billing_amount: 1200, billing_currency: "THB",
    merchant_name: "The Coconut Bar", merchant_city: "Pattaya", merchant_country: "TH",
    mcc_code: "5813", mcc_description: "Bars/Cocktail Lounges",
    transaction_type: "PURCHASE", authorization_code: "AUTH003", reference_number: "REF-003",
    policy_result: "AUTO_REJECTED", policy_reason: "MCC 5813 is auto-rejected per company policy",
    processing_status: "PROCESSED", created_at: "2026-02-27T10:00:00Z",
  },
  {
    id: "bt-004", file_id: "file-001", transaction_id: "TXN-2026022804",
    cardholder_employee_id: "EMP003", cardholder_name: "Nattapong Kaewkla",
    transaction_date: "2026-02-25", posting_date: "2026-02-26",
    billing_amount: 35000, billing_currency: "THB",
    merchant_name: "Thai Airways", merchant_city: "Bangkok", merchant_country: "TH",
    mcc_code: "4511", mcc_description: "Airlines/Air Carriers",
    transaction_type: "PURCHASE", authorization_code: "AUTH004", reference_number: "REF-004",
    policy_result: "REQUIRES_APPROVAL", policy_reason: "Airline tickets require manager approval",
    processing_status: "NEW", created_at: "2026-02-26T14:00:00Z",
  },
  {
    id: "bt-005", file_id: "file-002", transaction_id: "TXN-2026022805",
    cardholder_employee_id: "EMP002", cardholder_name: "Wanida Srisuk",
    transaction_date: "2026-02-24", posting_date: "2026-02-25",
    billing_amount: 890, billing_currency: "THB",
    merchant_name: "Tops Supermarket", merchant_city: "Bangkok", merchant_country: "TH",
    mcc_code: "5411", mcc_description: "Grocery Stores/Supermarkets",
    transaction_type: "PURCHASE", authorization_code: "AUTH005", reference_number: "REF-005",
    policy_result: "REQUIRES_APPROVAL", policy_reason: "Grocery purchases require approval",
    processing_status: "NEW", created_at: "2026-02-25T09:00:00Z",
  },
  {
    id: "bt-006", file_id: "file-002", transaction_id: "TXN-2026022806",
    cardholder_employee_id: "EMP004", cardholder_name: "Pitchaya Ruangrit",
    transaction_date: "2026-02-23", posting_date: "2026-02-24",
    billing_amount: 15800, billing_currency: "THB",
    merchant_name: "Siam Paragon Jewel", merchant_city: "Bangkok", merchant_country: "TH",
    mcc_code: "5944", mcc_description: "Jewelry/Watch/Clock Stores",
    transaction_type: "PURCHASE", authorization_code: "AUTH006", reference_number: "REF-006",
    policy_result: "AUTO_REJECTED", policy_reason: "MCC 5944 personal purchases auto-rejected",
    processing_status: "ERROR", created_at: "2026-02-24T11:00:00Z",
  },
  {
    id: "bt-007", file_id: "file-002", transaction_id: "TXN-2026022807",
    cardholder_employee_id: "EMP001", cardholder_name: "Somchai Jaidee",
    transaction_date: "2026-02-22", posting_date: "2026-02-23",
    billing_amount: 2800, billing_currency: "THB",
    merchant_name: "Sushi Hiro Restaurant", merchant_city: "Bangkok", merchant_country: "TH",
    mcc_code: "5812", mcc_description: "Eating Places/Restaurants",
    transaction_type: "PURCHASE", authorization_code: "AUTH007", reference_number: "REF-007",
    policy_result: "AUTO_APPROVED", policy_reason: "Amount within restaurant threshold 3,000",
    processing_status: "PROCESSED", created_at: "2026-02-23T13:00:00Z",
  },
  {
    id: "bt-008", file_id: "file-002", transaction_id: "TXN-2026022808",
    cardholder_employee_id: "EMP003", cardholder_name: "Nattapong Kaewkla",
    transaction_date: "2026-02-22", posting_date: "2026-02-23",
    billing_amount: 1800, billing_currency: "THB",
    merchant_name: "PTT Station Sukhumvit", merchant_city: "Bangkok", merchant_country: "TH",
    mcc_code: "5541", mcc_description: "Service Stations",
    transaction_type: "PURCHASE", authorization_code: "AUTH008", reference_number: "REF-008",
    policy_result: "AUTO_APPROVED", policy_reason: "Amount within fuel threshold 2,000",
    processing_status: "PROCESSED", created_at: "2026-02-23T13:00:00Z",
  },
];

export const mockCardholders = [
  { employee_id: "EMP001", name: "Somchai Jaidee" },
  { employee_id: "EMP002", name: "Wanida Srisuk" },
  { employee_id: "EMP003", name: "Nattapong Kaewkla" },
  { employee_id: "EMP004", name: "Pitchaya Ruangrit" },
];
