import { BankTransaction, MccPolicyMaster } from "./corporate-card-types";

export const mockMccPolicies: MccPolicyMaster[] = [
  { mcc_code: "3501", description: "Holiday Inn", category: "Hotel", policy_type: "AUTO_APPROVE", threshold_amount: 5000, currency: "THB", active_flag: true, updated_at: "2026-02-20T10:00:00Z" },
  { mcc_code: "4121", description: "Taxicabs/Limousines", category: "Transportation", policy_type: "AUTO_APPROVE", threshold_amount: 1500, currency: "THB", active_flag: true, updated_at: "2026-02-18T08:30:00Z" },
  { mcc_code: "5411", description: "Grocery Stores/Supermarkets", category: "Meals & Entertainment", policy_type: "REQUIRES_APPROVAL", threshold_amount: null, currency: "THB", active_flag: true, updated_at: "2026-02-15T14:00:00Z" },
  { mcc_code: "5812", description: "Eating Places/Restaurants", category: "Meals & Entertainment", policy_type: "AUTO_APPROVE", threshold_amount: 3000, currency: "THB", active_flag: true, updated_at: "2026-02-10T09:00:00Z" },
  { mcc_code: "5813", description: "Bars/Cocktail Lounges", category: "Meals & Entertainment", policy_type: "AUTO_REJECT", threshold_amount: null, currency: "THB", active_flag: true, updated_at: "2026-02-12T11:00:00Z" },
  { mcc_code: "7011", description: "Hotels/Motels/Resorts", category: "Hotel", policy_type: "AUTO_APPROVE", threshold_amount: 8000, currency: "THB", active_flag: true, updated_at: "2026-02-14T16:00:00Z" },
  { mcc_code: "7832", description: "Motion Picture Theaters", category: "Entertainment", policy_type: "AUTO_REJECT", threshold_amount: null, currency: "THB", active_flag: false, updated_at: "2026-01-30T10:00:00Z" },
  { mcc_code: "4511", description: "Airlines/Air Carriers", category: "Transportation", policy_type: "REQUIRES_APPROVAL", threshold_amount: null, currency: "THB", active_flag: true, updated_at: "2026-02-22T12:00:00Z" },
  { mcc_code: "5944", description: "Jewelry/Watch/Clock Stores", category: "Personal", policy_type: "AUTO_REJECT", threshold_amount: null, currency: "THB", active_flag: true, updated_at: "2026-02-01T09:00:00Z" },
  { mcc_code: "5541", description: "Service Stations", category: "Transportation", policy_type: "AUTO_APPROVE", threshold_amount: 2000, currency: "THB", active_flag: true, updated_at: "2026-02-19T15:00:00Z" },
];

export const mockBankTransactions: BankTransaction[] = [
  {
    id: "bt-001", file_id: "file-001", transaction_id: "TXN-2026022801",
    cardholder_employee_id: "EMP001", cardholder_name: "Somchai Jaidee",
    transaction_date: "2026-02-28", posting_date: "2026-02-28",
    billing_amount: 2500, billing_currency: "THB",
    merchant_name: "Grab Taxi", merchant_city: "Bangkok", merchant_country: "TH",
    mcc_code: "4121", mcc_description: "Taxicabs/Limousines",
    transaction_type: "PURCHASE", authorization_code: "AUTH001", reference_number: "REF-001",
    policy_result: "AUTO_APPROVED", policy_reason: "Amount 2,500 exceeds threshold 1,500 but within daily limit",
    processing_status: "PROCESSED", created_at: "2026-02-28T08:00:00Z",
  },
  {
    id: "bt-002", file_id: "file-001", transaction_id: "TXN-2026022802",
    cardholder_employee_id: "EMP002", cardholder_name: "Wanida Srisuk",
    transaction_date: "2026-02-27", posting_date: "2026-02-28",
    billing_amount: 4500, billing_currency: "THB",
    merchant_name: "Novotel Bangkok", merchant_city: "Bangkok", merchant_country: "TH",
    mcc_code: "7011", mcc_description: "Hotels/Motels/Resorts",
    transaction_type: "PURCHASE", authorization_code: "AUTH002", reference_number: "REF-002",
    policy_result: "AUTO_APPROVED", policy_reason: "Amount within hotel threshold 8,000",
    processing_status: "PROCESSED", created_at: "2026-02-28T08:05:00Z",
  },
  {
    id: "bt-003", file_id: "file-001", transaction_id: "TXN-2026022803",
    cardholder_employee_id: "EMP001", cardholder_name: "Somchai Jaidee",
    transaction_date: "2026-02-26", posting_date: "2026-02-27",
    billing_amount: 1200, billing_currency: "THB",
    merchant_name: "The Coconut Bar", merchant_city: "Pattaya", merchant_country: "TH",
    mcc_code: "5813", mcc_description: "Bars/Cocktail Lounges",
    transaction_type: "PURCHASE", authorization_code: "AUTH003", reference_number: "REF-003",
    policy_result: "AUTO_REJECTED", policy_reason: "MCC 5813 is auto-rejected per company policy",
    processing_status: "PROCESSED", created_at: "2026-02-27T10:00:00Z",
  },
  {
    id: "bt-004", file_id: "file-001", transaction_id: "TXN-2026022804",
    cardholder_employee_id: "EMP003", cardholder_name: "Nattapong Kaewkla",
    transaction_date: "2026-02-25", posting_date: "2026-02-26",
    billing_amount: 35000, billing_currency: "THB",
    merchant_name: "Thai Airways", merchant_city: "Bangkok", merchant_country: "TH",
    mcc_code: "4511", mcc_description: "Airlines/Air Carriers",
    transaction_type: "PURCHASE", authorization_code: "AUTH004", reference_number: "REF-004",
    policy_result: "REQUIRES_APPROVAL", policy_reason: "Airline tickets require manager approval",
    processing_status: "NEW", created_at: "2026-02-26T14:00:00Z",
  },
  {
    id: "bt-005", file_id: "file-002", transaction_id: "TXN-2026022805",
    cardholder_employee_id: "EMP002", cardholder_name: "Wanida Srisuk",
    transaction_date: "2026-02-24", posting_date: "2026-02-25",
    billing_amount: 890, billing_currency: "THB",
    merchant_name: "Tops Supermarket", merchant_city: "Bangkok", merchant_country: "TH",
    mcc_code: "5411", mcc_description: "Grocery Stores/Supermarkets",
    transaction_type: "PURCHASE", authorization_code: "AUTH005", reference_number: "REF-005",
    policy_result: "REQUIRES_APPROVAL", policy_reason: "Grocery purchases require approval",
    processing_status: "NEW", created_at: "2026-02-25T09:00:00Z",
  },
  {
    id: "bt-006", file_id: "file-002", transaction_id: "TXN-2026022806",
    cardholder_employee_id: "EMP004", cardholder_name: "Pitchaya Ruangrit",
    transaction_date: "2026-02-23", posting_date: "2026-02-24",
    billing_amount: 15800, billing_currency: "THB",
    merchant_name: "Siam Paragon Jewel", merchant_city: "Bangkok", merchant_country: "TH",
    mcc_code: "5944", mcc_description: "Jewelry/Watch/Clock Stores",
    transaction_type: "PURCHASE", authorization_code: "AUTH006", reference_number: "REF-006",
    policy_result: "AUTO_REJECTED", policy_reason: "MCC 5944 personal purchases auto-rejected",
    processing_status: "ERROR", created_at: "2026-02-24T11:00:00Z",
  },
  {
    id: "bt-007", file_id: "file-002", transaction_id: "TXN-2026022807",
    cardholder_employee_id: "EMP001", cardholder_name: "Somchai Jaidee",
    transaction_date: "2026-02-22", posting_date: "2026-02-23",
    billing_amount: 2800, billing_currency: "THB",
    merchant_name: "Sushi Hiro Restaurant", merchant_city: "Bangkok", merchant_country: "TH",
    mcc_code: "5812", mcc_description: "Eating Places/Restaurants",
    transaction_type: "PURCHASE", authorization_code: "AUTH007", reference_number: "REF-007",
    policy_result: "AUTO_APPROVED", policy_reason: "Amount within restaurant threshold 3,000",
    processing_status: "PROCESSED", created_at: "2026-02-23T13:00:00Z",
  },
  {
    id: "bt-008", file_id: "file-002", transaction_id: "TXN-2026022808",
    cardholder_employee_id: "EMP003", cardholder_name: "Nattapong Kaewkla",
    transaction_date: "2026-02-22", posting_date: "2026-02-23",
    billing_amount: 1800, billing_currency: "THB",
    merchant_name: "PTT Station Sukhumvit", merchant_city: "Bangkok", merchant_country: "TH",
    mcc_code: "5541", mcc_description: "Service Stations",
    transaction_type: "PURCHASE", authorization_code: "AUTH008", reference_number: "REF-008",
    policy_result: "AUTO_APPROVED", policy_reason: "Amount within fuel threshold 2,000",
    processing_status: "PROCESSED", created_at: "2026-02-23T07:30:00Z",
  },
];

export const mockCardholders = [
  { employee_id: "EMP001", name: "Somchai Jaidee" },
  { employee_id: "EMP002", name: "Wanida Srisuk" },
  { employee_id: "EMP003", name: "Nattapong Kaewkla" },
  { employee_id: "EMP004", name: "Pitchaya Ruangrit" },
];
