import { ClaimHeader, User, BankTransaction } from "./types";

export const currentUser: User = {
  id: "u1",
  employeeCode: "EMP001",
  name: "Somchai Jaidee",
  email: "somchai@company.com",
  roles: ["Cardholder"],
  branch: "Bangkok",
  department: "Sales",
  costCenter: "CC-SALES-01",
  position: "Sales Executive",
  telephone: "02-123-4567",
};

export const users: User[] = [
  currentUser,
  { id: "u2", employeeCode: "EMP002", name: "Somying Kaewsai", email: "somying@company.com", roles: ["Cardholder", "Approver"], branch: "Bangkok", department: "Sales", costCenter: "CC-SALES-01", position: "Sales Manager" },
  { id: "u3", employeeCode: "EMP003", name: "Wichai Charoen", email: "wichai@company.com", roles: ["Cardholder"], branch: "Chiang Mai", department: "Engineering", costCenter: "CC-ENG-01", position: "Software Engineer" },
  { id: "u4", employeeCode: "ACC001", name: "Pim Dee", email: "pim@company.com", roles: ["Cardholder"], branch: "Bangkok", department: "Finance", costCenter: "CC-FIN-01", position: "Senior Accountant" },
  { id: "u5", employeeCode: "MGR001", name: "Thana Pitak", email: "thana@company.com", roles: ["Admin"], branch: "Bangkok", department: "Management", costCenter: "CC-MGT-01", position: "Director" },
  { id: "u6", employeeCode: "SUP001", name: "Nattapong Srisuk", email: "nattapong@company.com", roles: ["Admin", "Approver", "Cardholder"], branch: "Bangkok", department: "Management", costCenter: "CC-MGT-01", position: "VP Operations" },
  { id: "u7", employeeCode: "FIN001", name: "Aor (Finance Team)", email: "aor@company.com", roles: ["Cardholder"], branch: "Bangkok", department: "Finance", costCenter: "CC-FIN-01", position: "Finance Officer" },
];

/** Demo login accounts with their passwords */
export const demoAccounts = [
  { email: "nattapong@company.com", password: "demo", userId: "u6", label: "Admin+Approver+Cardholder" },
  { email: "somchai@company.com", password: "demo", userId: "u1", label: "Cardholder" },
  { email: "somying@company.com", password: "demo", userId: "u2", label: "Cardholder + Approver" },
  { email: "pim@company.com", password: "demo", userId: "u4", label: "Cardholder (Finance)" },
  { email: "thana@company.com", password: "demo", userId: "u5", label: "Admin" },
];

export const mockClaims: ClaimHeader[] = [
  {
    id: "c1", claimNo: "TXN20250129001", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Taxicabs and Limousines", merchantName: "GRAB TAXI", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 1500, totalVat: 0, status: "Pending Invoice", createdDate: "2026-02-28", submittedDate: null,
    lines: [], approvalHistory: [], comments: [],
  },
  {
    id: "c2", claimNo: "TXN20250129002", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Hotels and Motels", merchantName: "MARRIOTT HOTEL BKK", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 3500, totalVat: 0, status: "Pending Invoice", createdDate: "2026-02-28", submittedDate: null,
    lines: [], approvalHistory: [], comments: [],
  },
  {
    id: "c3", claimNo: "TXN20250129003", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Service Stations", merchantName: "PTT GAS STATION", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 850, totalVat: 0, status: "Pending Invoice", createdDate: "2026-02-28", submittedDate: null,
    lines: [], approvalHistory: [], comments: [],
  },
  {
    id: "c4", claimNo: "TXN20250129004", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Eating Places and Restaurants", merchantName: "SOMTUM RESTAURANT", currency: "THB", paymentMethod: "Cash",
    totalAmount: 1250, totalVat: 0, status: "Pending Invoice", createdDate: "2026-02-28", submittedDate: null,
    lines: [], approvalHistory: [], comments: [],
  },
  {
    id: "c5", claimNo: "TXN20250129005", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Airlines", merchantName: "THAI AIRWAYS", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 15000, totalVat: 0, status: "Pending Invoice", createdDate: "2026-02-28", submittedDate: null,
    lines: [], approvalHistory: [], comments: [],
  },
  {
    id: "r1", claimNo: "TXN20260227021", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Amusement Parks", merchantName: "Siam Amazing Park", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 7900, totalVat: 0, status: "Auto Reject", createdDate: "2026-02-27", submittedDate: "2026-02-27",
    lines: [], approvalHistory: [], comments: [],
  },
  {
    id: "r2", claimNo: "TXN20260227002", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Tourist Attractions", merchantName: "Tiger Kingdom", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 4500, totalVat: 0, status: "Auto Reject", createdDate: "2026-02-27", submittedDate: "2026-02-27",
    lines: [], approvalHistory: [], comments: [],
  },
  {
    id: "r3", claimNo: "TXN20260227053", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Dance Halls", merchantName: "The Street", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 2500, totalVat: 0, status: "Auto Reject", createdDate: "2026-02-27", submittedDate: "2026-02-27",
    lines: [], approvalHistory: [], comments: [],
  },
  {
    id: "r4", claimNo: "TXN20260227114", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Drinking Places (Bars)", merchantName: "The Nine", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 1250, totalVat: 0, status: "Reject", createdDate: "2026-02-27", submittedDate: "2026-02-27",
    lines: [], approvalHistory: [], comments: [],
  },
  {
    id: "r5", claimNo: "TXN20260227025", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Sporting and Recreational Camps", merchantName: "Stone Hill Golf Club", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 55000, totalVat: 0, status: "Final Rejected", createdDate: "2026-02-27", submittedDate: "2026-02-27",
    lines: [], approvalHistory: [], comments: [],
  },
  {
    id: "a1", claimNo: "TXN20260227071", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Grocery Stores", merchantName: "Top", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 799, totalVat: 0, status: "Auto Approved", createdDate: "2026-02-27", submittedDate: "2026-02-27",
    lines: [], approvalHistory: [], comments: [],
  },
  {
    id: "a2", claimNo: "TXN20260227078", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Fast Food Restaurants", merchantName: "KFC", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 279, totalVat: 0, status: "Auto Approved", createdDate: "2026-02-27", submittedDate: "2026-02-27",
    lines: [], approvalHistory: [], comments: [],
  },
  {
    id: "a3", claimNo: "TXN20260227013", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Eating Places and Restaurants", merchantName: "Suki Teenoi", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 499, totalVat: 0, status: "Auto Approved", createdDate: "2026-02-27", submittedDate: "2026-02-27",
    lines: [], approvalHistory: [], comments: [],
  },
  {
    id: "a4", claimNo: "TXN20260227124", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Car Rental Agencies", merchantName: "Good Car Service", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 3000, totalVat: 0, status: "Manager Approved", createdDate: "2026-02-27", submittedDate: "2026-02-27",
    lines: [], approvalHistory: [], comments: [],
  },
  {
    id: "a5", claimNo: "TXN20260227065", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Hospitals", merchantName: "Rama 9 Hospital", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 2500, totalVat: 0, status: "Manager Approved", createdDate: "2026-02-27", submittedDate: "2026-02-27",
    lines: [], approvalHistory: [], comments: [],
  },
  {
    id: "c6", claimNo: "TXN20250128001", requesterId: "u3", requesterName: "Wichai Charoen",
    company: "ABC Co., Ltd.", branch: "Chiang Mai", department: "9993010460 Finance and Accounting", costCenter: "CC-ENG-01",
    purpose: "Taxi to client site", merchantName: "GRAB TAXI", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 1850, totalVat: 0, status: "Pending Invoice", createdDate: "2026-02-25", submittedDate: "2026-02-26",
    lines: [], approvalHistory: [{ stepNo: 1, approverId: "u1", approverName: "Somchai Jaidee", action: "Pending", comment: "", actionDate: null }], comments: [],
  },
  {
    id: "c7", claimNo: "TXN20250128002", requesterId: "u2", requesterName: "Somying Kaewsai",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Business dinner with client", merchantName: "BANYAN TREE RESTAURANT", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 8500, totalVat: 595, status: "Pending Invoice", createdDate: "2026-02-24", submittedDate: "2026-02-25",
    lines: [], approvalHistory: [{ stepNo: 1, approverId: "u1", approverName: "Somchai Jaidee", action: "Pending", comment: "", actionDate: null }], comments: [],
  },
  {
    id: "c8", claimNo: "TXN20250127001", requesterId: "u3", requesterName: "Wichai Charoen",
    company: "ABC Co., Ltd.", branch: "Chiang Mai", department: "9993010460 Finance and Accounting", costCenter: "CC-ENG-01",
    purpose: "Flight to Bangkok for meeting", merchantName: "THAI AIRWAYS", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 12500, totalVat: 0, status: "Pending Invoice", createdDate: "2026-02-23", submittedDate: "2026-02-24",
    lines: [], approvalHistory: [{ stepNo: 1, approverId: "u1", approverName: "Somchai Jaidee", action: "Pending", comment: "", actionDate: null }], comments: [],
  },
  {
    id: "c9", claimNo: "TXN20250127002", requesterId: "u2", requesterName: "Somying Kaewsai",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Hotel for regional meeting", merchantName: "NOVOTEL BANGKOK", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 4200, totalVat: 294, status: "Pending Invoice", createdDate: "2026-02-22", submittedDate: "2026-02-23",
    lines: [], approvalHistory: [{ stepNo: 1, approverId: "u1", approverName: "Somchai Jaidee", action: "Pending", comment: "", actionDate: null }], comments: [],
  },
  {
    id: "c10", claimNo: "TXN20250126001", requesterId: "u3", requesterName: "Wichai Charoen",
    company: "ABC Co., Ltd.", branch: "Chiang Mai", department: "9993010460 Finance and Accounting", costCenter: "CC-ENG-01",
    purpose: "Office supplies for project", merchantName: "OfficeMate", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 3200, totalVat: 224, status: "Pending Invoice", createdDate: "2026-02-21", submittedDate: "2026-02-22",
    lines: [], approvalHistory: [{ stepNo: 1, approverId: "u1", approverName: "Somchai Jaidee", action: "Pending", comment: "", actionDate: null }], comments: [],
  },
  // Returned For Info claims (April 2026)
  {
    id: "rfi1", claimNo: "Transaction20260415001", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Taxicabs and Limousines", merchantName: "GRAB TAXI", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 1500, totalVat: 0, status: "Returned For Info", createdDate: "2026-04-01", submittedDate: "2026-04-01",
    corpTxnDocumentStatus: "PENDING_DOCUMENTS",
    lines: [], approvalHistory: [], comments: [],
  },
  {
    id: "rfi2", claimNo: "Transaction20260415002", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Hotels and Motels", merchantName: "MARRIOTT HOTEL BKK", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 3500, totalVat: 0, status: "Returned For Info", createdDate: "2026-04-02", submittedDate: "2026-04-02",
    corpTxnDocumentStatus: "PENDING_DOCUMENTS",
    lines: [], approvalHistory: [], comments: [],
  },
  {
    id: "rfi3", claimNo: "Transaction20260415003", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Eating Places and Restaurants", merchantName: "STARBUCKS", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 850, totalVat: 0, status: "Returned For Info", createdDate: "2026-04-03", submittedDate: "2026-04-03",
    corpTxnDocumentStatus: "VALIDATED",
    lines: [], approvalHistory: [], comments: [],
  },
  {
    id: "rfi4", claimNo: "Transaction20260415004", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Amusement Parks", merchantName: "Siam Amazing Park", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 7900, totalVat: 0, status: "Returned For Info", createdDate: "2026-04-04", submittedDate: "2026-04-04",
    corpTxnDocumentStatus: "PENDING_DOCUMENTS",
    lines: [], approvalHistory: [], comments: [],
  },
  {
    id: "rfi5", claimNo: "Transaction20260415005", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Airlines", merchantName: "THAI AIRWAYS", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 15000, totalVat: 0, status: "Returned For Info", createdDate: "2026-04-05", submittedDate: "2026-04-05",
    corpTxnDocumentStatus: "SUBMITTED",
    lines: [], approvalHistory: [], comments: [],
  },
  {
    id: "rfi6", claimNo: "Transaction20260415006", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Department Stores", merchantName: "CENTRAL DEPARTMENT", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 2300, totalVat: 0, status: "Returned For Info", createdDate: "2026-04-06", submittedDate: "2026-04-06",
    corpTxnDocumentStatus: "PENDING_DOCUMENTS",
    lines: [], approvalHistory: [], comments: [],
  },
  {
    id: "rfi7", claimNo: "Transaction20260415007", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Fast Food Restaurants", merchantName: "KFC", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 279, totalVat: 0, status: "Returned For Info", createdDate: "2026-04-07", submittedDate: "2026-04-07",
    corpTxnDocumentStatus: "PENDING_DOCUMENTS",
    lines: [], approvalHistory: [], comments: [],
  },
  // Pending Approval claims (for Approval Inbox)
  {
    id: "pa1", claimNo: "TXN20260301001", requesterId: "u6", requesterName: "Somying Prasertsuk",
    company: "CP Axtra Co., Ltd.", branch: "Bangkok", department: "Commercial — HoReCa", costCenter: "CC-COM-01",
    purpose: "Airline — Domestic (Bangkok → Chiang Mai, Sales Visit)", merchantName: "THAI AIRWAYS", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 8500, totalVat: 0, status: "Pending Approval", createdDate: "2026-03-01", submittedDate: "2026-03-01",
    lines: [], approvalHistory: [{ stepNo: 1, approverId: "u1", approverName: "Somchai Jaidee", action: "Pending", comment: "", actionDate: null }], comments: [],
  },
  {
    id: "pa2", claimNo: "TXN20260301002", requesterId: "u7", requesterName: "Nattapon Wichai",
    company: "CP Axtra Co., Ltd.", branch: "Bangkok", department: "Operations — Supply Chain", costCenter: "CC-OPS-01",
    purpose: "Car Rental (3 days, site inspection Rayong)", merchantName: "BUDGET CAR RENTAL", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 12000, totalVat: 0, status: "Pending Approval", createdDate: "2026-03-02", submittedDate: "2026-03-02",
    lines: [], approvalHistory: [{ stepNo: 1, approverId: "u1", approverName: "Somchai Jaidee", action: "Pending", comment: "", actionDate: null }], comments: [],
  },
  {
    id: "pa3", claimNo: "TXN20260305001", requesterId: "u8", requesterName: "Kannika Thongsuk",
    company: "CP Axtra Co., Ltd.", branch: "Bangkok", department: "Finance — Accounting", costCenter: "CC-FIN-01",
    purpose: "Airline — Overseas (Bangkok → Singapore, Regional Meeting)", merchantName: "SINGAPORE AIRLINES", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 42500, totalVat: 0, status: "Pending Approval", createdDate: "2026-03-05", submittedDate: "2026-03-05",
    lines: [], approvalHistory: [{ stepNo: 1, approverId: "u1", approverName: "Somchai Jaidee", action: "Pending", comment: "", actionDate: null }], comments: [],
  },
  {
    id: "pa4", claimNo: "TXN20260310001", requesterId: "u6", requesterName: "Somying Prasertsuk",
    company: "CP Axtra Co., Ltd.", branch: "Bangkok", department: "Commercial — HoReCa", costCenter: "CC-COM-01",
    purpose: "Car Rental (2 days, customer event Pattaya)", merchantName: "AVIS RENT A CAR", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 9200, totalVat: 0, status: "Pending Approval", createdDate: "2026-03-10", submittedDate: "2026-03-10",
    lines: [], approvalHistory: [{ stepNo: 1, approverId: "u1", approverName: "Somchai Jaidee", action: "Pending", comment: "", actionDate: null }], comments: [],
  },
  {
    id: "CLM-TEST-REJECT-001", claimNo: "CLM-2026-TEST-001", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "SINGAPORE AIRLINES", merchantName: "SINGAPORE AIRLINES", currency: "THB", paymentMethod: "Corporate Card",
    expenseTypeId: "et-2", subExpenseTypeId: "set-8", vatTypeId: "claim_100", glAccountId: "gl-9",
    totalAmount: 18224.00, totalVat: 0, status: "Reject", createdDate: "2026-05-10", submittedDate: "2026-05-10",
    lines: [], approvalHistory: [], comments: [],
    returnSource: "MANAGER_REJECT", returnedByUserId: "u2", returnedAt: "2026-05-11T16:22:00Z",
    returnMessage: "Travel approval letter doesn't match the trip dates on the booking. Please attach the corrected approval and resubmit.",
    resubmitCountMgr: 0,
    documentChecklistOverride: {
      required: [{ id: "dt-eticket-test", documentName: "E-Ticket / Flight ticket", isSupportDocument: false }],
      optional: [{ id: "dt-travel-insurance-test", documentName: "Travel Insurance Certificate", isSupportDocument: true }],
    },
  },
  {
    id: "CLM-TEST-RFI-001", claimNo: "CLM-2026-TEST-002", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Cloud Services", merchantName: "AMAZON WEB SERVICES", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 5420.50, totalVat: 0, status: "Returned For Info", createdDate: "2026-05-10", submittedDate: "2026-05-10",
    lines: [], approvalHistory: [], comments: [],
    returnSource: "MANAGER_RFI", returnedByUserId: "u2", returnedAt: "2026-05-11T17:45:00Z",
    returnMessage: "Can you justify this as a business expense and attach pre-approval from Director Y? What project does this AWS bill cover?",
  },
  {
    id: "CLM-TEST-FIN-001", claimNo: "CLM-2026-TEST-003", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Drinking Places (Bars)", merchantName: "IRON FAIRIES", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 3200.00, totalVat: 0, status: "Returned By Finance", createdDate: "2026-05-11", submittedDate: "2026-05-11",
    lines: [], approvalHistory: [], comments: [],
    returnSource: "FINANCE_RETURN", returnedByUserId: "u7", returnedAt: "2026-05-12T09:10:00Z",
    returnMessage: "Buyer Tax ID on the Full Tax Invoice is incorrect for CPAxtra — it shows '01095...' but our entity is '01075...'. Please request a corrected invoice from the vendor.",
  },
  {
    id: "CLM-TEST-FINAL-001", claimNo: "CLM-2026-TEST-004", requesterId: "u1", requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.", branch: "Bangkok", department: "9993010460 Finance and Accounting", costCenter: "CC-SALES-01",
    purpose: "Office Supplies", merchantName: "B2S", currency: "THB", paymentMethod: "Corporate Card",
    totalAmount: 890.00, totalVat: 0, status: "Final Rejected", createdDate: "2026-05-09", submittedDate: "2026-05-09",
    lines: [], approvalHistory: [], comments: [],
    returnSource: "MANAGER_REJECT", returnedByUserId: "u2", returnedAt: "2026-05-12T11:00:00Z",
    returnMessage: "The resubmitted invoice still does not match the card transaction amount. This expense cannot be approved.",
    resubmitCountMgr: 1,
    cardholderNote: "Bought a notebook for client meeting prep. Vendor refused to issue a corrected invoice.",
  },
];
export const mockBankTransactions: BankTransaction[] = [
  { id: "TXN-001", txnDate: "2025-02-01", amount: 15200, merchant: "Thai Airways", cardholderName: "Somchai Jaidee", reference: "REF-001", status: "Matched", linkedClaimId: "c1" },
  { id: "TXN-002", txnDate: "2025-02-03", amount: 850, merchant: "Starbucks Siam", cardholderName: "Somying Kaewsai", reference: "REF-002", status: "Unmatched", linkedClaimId: null },
  { id: "TXN-003", txnDate: "2025-02-05", amount: 12000, merchant: "Amazon Web Services", cardholderName: "Wichai Charoen", reference: "REF-003", status: "Partially Matched", linkedClaimId: "c6" },
  { id: "TXN-004", txnDate: "2025-02-06", amount: 320, merchant: "Grab Transport", cardholderName: "Napa Jamsai", reference: "REF-004", status: "Exception", linkedClaimId: null },
];

export const branches = ["Bangkok", "Chiang Mai", "Phuket", "Khon Kaen"];
export const departments = ["Sales", "Marketing", "Engineering", "HR", "Finance", "Management", "Operations", "IT"];
export const costCenters = ["CC-SALES-01", "CC-MKT-01", "CC-ENG-01", "CC-HR-01", "CC-FIN-01", "CC-MGT-01", "CC-OPS-01", "CC-IT-01"];
export const projects = ["PRJ-001", "PRJ-002", "PRJ-003", "PRJ-DEV", "PRJ-MKT"];
export const expenseTypes = ["Travel", "Meals", "Office Supplies", "Transportation", "Training", "Entertainment", "Communication", "Other"] as const;
export const paymentMethods = ["Cash", "Corporate Card", "Personal Card", "Bank Transfer"] as const;
