// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.5";

// src/lib/mcp/tools/app-overview.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.5";

// src/lib/mcp/util.ts
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) throw new Error("Authenticated caller required");
}
function jsonResult(label, data) {
  return { content: [{ type: "text", text: `${label}
${JSON.stringify(data, null, 2)}` }] };
}
function matches(haystack, q) {
  if (!q) return true;
  const needle = q.toLowerCase();
  return haystack.some((v) => String(v ?? "").toLowerCase().includes(needle));
}

// src/lib/mcp/tools/app-overview.ts
var OVERVIEW = {
  app: "Card Expense Management (Corporate Credit Card & Fleet Card)",
  design: {
    colors: "White and red corporate palette; blue (#306FC7) for links/Created status",
    font: "Inter / sans-serif; Thai text uses a Thai-capable font",
    language: "English-only UI; Thai only for names, addresses, invoice content",
    dates: "DD/MM/YYYY in Buddhist Era (CE + 543)",
    currency: "\u0E3F / THB with thousand separators"
  },
  roles: {
    Cardholder: "My Expense, Card Requests, Notifications",
    Approver: "My Expense, Card Requests, Approval Inbox",
    Admin: "All modules incl. Accounting Review, Bank Transactions, Admin settings"
  },
  pages: [
    "/claims \u2014 My Expense list (Credit/Fleet filters, summary bar, approval/document badges)",
    "/claims/:id \u2014 Claim detail (receipt upload, OCR validation, VAT/GL entry, audit trail)",
    "/approvals \u2014 Approval Inbox (batch actions, request more info)",
    "/accounting \u2014 Accounting Review (Fleet Card = Auto Approved, ERP sync vs exceptions)",
    "/bank-transactions \u2014 Bank file import and transactions",
    "/card-requests \u2014 HR card request list and form",
    "/admin \u2014 Admin settings: Card Management, Data Scope, Roles & Permissions, Expense Types, GL Accounts, Projects, Policy, Notifications, HRIS Sync Exceptions, Input VAT Report, Upload Fleet Card E Tax Invoice"
  ],
  cardStatuses: ["Created", "Handed Over", "Received", "Pending Activation", "Active", "Reassigned", "Rejected"],
  rules: [
    "One receipt PDF per expense line; OCR validation required before submit",
    "Corporate cards masked to last 4 digits",
    "Data Scope limits which card types a role sees in Card Management; Admin sees all",
    "Fleet Card transactions always show Approval Status 'Auto Approved'"
  ],
  note: "All data in this app is sample data."
};
var app_overview_default = defineTool({
  name: "get_app_overview",
  title: "Get app overview",
  description: "Describe the app's modules, pages, roles, statuses, business rules and design conventions.",
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_args, ctx) => {
    requireAuth(ctx);
    return jsonResult("App overview", OVERVIEW);
  }
});

// src/lib/mcp/tools/list-card-transactions.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@3.0.5";
import { z } from "npm:zod@^4.6.5";

// src/lib/mock-dates.ts
var SOURCE_START = Date.UTC(2026, 0, 1);
var SOURCE_END = Date.UTC(2026, 4, 31, 23, 59, 59);
var LAST_MONTH_SHARE = 0.6;
var pad = (n) => String(n).padStart(2, "0");
var toIsoDate = (d) => `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
function firstDayOfLastMonth(now = /* @__PURE__ */ new Date()) {
  return new Date(now.getFullYear(), now.getMonth() - 1, 1);
}
var SEED_DAYS = ["2026-01-01", "2026-01-30", "2026-02-01", "2026-02-10", "2026-02-12", "2026-02-14", "2026-02-15", "2026-02-18", "2026-02-19", "2026-02-20", "2026-02-21", "2026-02-22", "2026-02-23", "2026-02-24", "2026-02-25", "2026-02-26", "2026-02-27", "2026-02-28", "2026-03-01", "2026-03-02", "2026-03-03", "2026-03-04", "2026-03-05", "2026-03-06", "2026-03-07", "2026-03-08", "2026-03-10", "2026-03-11", "2026-03-15", "2026-03-16", "2026-03-17", "2026-04-01", "2026-04-02", "2026-04-03", "2026-04-04", "2026-04-05", "2026-04-06", "2026-04-07", "2026-04-08", "2026-04-18", "2026-04-20", "2026-04-21", "2026-04-22", "2026-04-23", "2026-04-28", "2026-05-01", "2026-05-02", "2026-05-03", "2026-05-04", "2026-05-05", "2026-05-06", "2026-05-07", "2026-05-08", "2026-05-09", "2026-05-10", "2026-05-11", "2026-05-12", "2026-05-13", "2026-05-14", "2026-05-15", "2026-05-16", "2026-05-17"].map((d) => Date.UTC(+d.slice(0, 4), +d.slice(5, 7) - 1, +d.slice(8, 10), 12));
function rankOf(t) {
  if (t <= SEED_DAYS[0]) return 0;
  const last = SEED_DAYS.length - 1;
  if (t >= SEED_DAYS[last]) return last;
  let i = 0;
  while (SEED_DAYS[i + 1] < t) i++;
  return i + (t - SEED_DAYS[i]) / (SEED_DAYS[i + 1] - SEED_DAYS[i]);
}
function mapTime(t, now = /* @__PURE__ */ new Date()) {
  const frac = rankOf(t) / (SEED_DAYS.length - 1);
  const lastStart = firstDayOfLastMonth(now).getTime();
  const thisStart = new Date(now.getFullYear(), now.getMonth(), 1).getTime();
  if (frac < LAST_MONTH_SHARE) {
    return lastStart + frac / LAST_MONTH_SHARE * (thisStart - 1 - lastStart);
  }
  return thisStart + (frac - LAST_MONTH_SHARE) / (1 - LAST_MONTH_SHARE) * (now.getTime() - thisStart);
}
var DATE_RE = /^(\d{4})-(\d{2})-(\d{2})$/;
var DATETIME_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/;
function rebaseMockDate(value) {
  const m = DATE_RE.exec(value);
  if (m) {
    const t = Date.UTC(+m[1], +m[2] - 1, +m[3], 12);
    if (t < SOURCE_START || t > SOURCE_END) return value;
    return toIsoDate(new Date(mapTime(t)));
  }
  if (DATETIME_RE.test(value)) {
    const t = new Date(value).getTime();
    if (isNaN(t) || t < SOURCE_START || t > SOURCE_END) return value;
    return new Date(Math.min(mapTime(t), Date.now())).toISOString();
  }
  return value;
}
function rebaseMockDates(data) {
  const walk = (v, key) => {
    if (typeof v === "string") return key && /id$|Id$|No$|number$|Number$/.test(key) ? v : rebaseMockDate(v);
    if (Array.isArray(v)) return v.map((x) => walk(x));
    if (v && typeof v === "object") {
      for (const k of Object.keys(v)) {
        v[k] = walk(v[k], k);
      }
      return v;
    }
    return v;
  };
  return walk(data);
}

// src/lib/corporate-card-mock-data.ts
var mockBankTransactions = rebaseMockDates([
  {
    id: "bt-001",
    file_id: "file-001",
    transaction_id: "TXN-2026022801",
    cardholder_employee_id: "EMP001",
    cardholder_name: "Somchai Jaidee",
    transaction_date: "2026-02-28",
    posting_date: "2026-02-28",
    billing_amount: 2500,
    billing_currency: "THB",
    merchant_name: "Grab Taxi",
    merchant_city: "Bangkok",
    merchant_country: "TH",
    mcc_code: "4121",
    mcc_description: "Taxicabs/Limousines",
    transaction_type: "PURCHASE",
    authorization_code: "AUTH001",
    reference_number: "REF-001",
    policy_result: "AUTO_APPROVED",
    policy_reason: "Amount 2,500 exceeds threshold 1,500 but within daily limit",
    processing_status: "PROCESSED",
    created_at: "2026-02-28T08:00:00Z"
  },
  {
    id: "bt-002",
    file_id: "file-001",
    transaction_id: "TXN-2026022802",
    cardholder_employee_id: "EMP002",
    cardholder_name: "Wanida Srisuk",
    transaction_date: "2026-02-27",
    posting_date: "2026-02-28",
    billing_amount: 4500,
    billing_currency: "THB",
    merchant_name: "Novotel Bangkok",
    merchant_city: "Bangkok",
    merchant_country: "TH",
    mcc_code: "7011",
    mcc_description: "Hotels/Motels/Resorts",
    transaction_type: "PURCHASE",
    authorization_code: "AUTH002",
    reference_number: "REF-002",
    policy_result: "AUTO_APPROVED",
    policy_reason: "Amount within hotel threshold 8,000",
    processing_status: "PROCESSED",
    created_at: "2026-02-28T08:00:00Z"
  },
  {
    id: "bt-003",
    file_id: "file-001",
    transaction_id: "TXN-2026022803",
    cardholder_employee_id: "EMP001",
    cardholder_name: "Somchai Jaidee",
    transaction_date: "2026-02-26",
    posting_date: "2026-02-27",
    billing_amount: 1200,
    billing_currency: "THB",
    merchant_name: "The Coconut Bar",
    merchant_city: "Pattaya",
    merchant_country: "TH",
    mcc_code: "5813",
    mcc_description: "Bars/Cocktail Lounges",
    transaction_type: "PURCHASE",
    authorization_code: "AUTH003",
    reference_number: "REF-003",
    policy_result: "AUTO_REJECTED",
    policy_reason: "MCC 5813 is auto-rejected per company policy",
    processing_status: "PROCESSED",
    created_at: "2026-02-27T10:00:00Z"
  },
  {
    id: "bt-004",
    file_id: "file-001",
    transaction_id: "TXN-2026022804",
    cardholder_employee_id: "EMP003",
    cardholder_name: "Nattapong Kaewkla",
    transaction_date: "2026-02-25",
    posting_date: "2026-02-26",
    billing_amount: 35e3,
    billing_currency: "THB",
    merchant_name: "Thai Airways",
    merchant_city: "Bangkok",
    merchant_country: "TH",
    mcc_code: "4511",
    mcc_description: "Airlines/Air Carriers",
    transaction_type: "PURCHASE",
    authorization_code: "AUTH004",
    reference_number: "REF-004",
    policy_result: "REQUIRES_APPROVAL",
    policy_reason: "Airline tickets require manager approval",
    processing_status: "NEW",
    created_at: "2026-02-26T14:00:00Z"
  },
  {
    id: "bt-005",
    file_id: "file-002",
    transaction_id: "TXN-2026022805",
    cardholder_employee_id: "EMP002",
    cardholder_name: "Wanida Srisuk",
    transaction_date: "2026-02-24",
    posting_date: "2026-02-25",
    billing_amount: 890,
    billing_currency: "THB",
    merchant_name: "Tops Supermarket",
    merchant_city: "Bangkok",
    merchant_country: "TH",
    mcc_code: "5411",
    mcc_description: "Grocery Stores/Supermarkets",
    transaction_type: "PURCHASE",
    authorization_code: "AUTH005",
    reference_number: "REF-005",
    policy_result: "REQUIRES_APPROVAL",
    policy_reason: "Grocery purchases require approval",
    processing_status: "NEW",
    created_at: "2026-02-25T09:00:00Z"
  },
  {
    id: "bt-006",
    file_id: "file-002",
    transaction_id: "TXN-2026022806",
    cardholder_employee_id: "EMP004",
    cardholder_name: "Pitchaya Ruangrit",
    transaction_date: "2026-02-23",
    posting_date: "2026-02-24",
    billing_amount: 15800,
    billing_currency: "THB",
    merchant_name: "Siam Paragon Jewel",
    merchant_city: "Bangkok",
    merchant_country: "TH",
    mcc_code: "5944",
    mcc_description: "Jewelry/Watch/Clock Stores",
    transaction_type: "PURCHASE",
    authorization_code: "AUTH006",
    reference_number: "REF-006",
    policy_result: "AUTO_REJECTED",
    policy_reason: "MCC 5944 personal purchases auto-rejected",
    processing_status: "ERROR",
    created_at: "2026-02-24T11:00:00Z"
  },
  {
    id: "bt-007",
    file_id: "file-002",
    transaction_id: "TXN-2026022807",
    cardholder_employee_id: "EMP001",
    cardholder_name: "Somchai Jaidee",
    transaction_date: "2026-02-22",
    posting_date: "2026-02-23",
    billing_amount: 2800,
    billing_currency: "THB",
    merchant_name: "Sushi Hiro Restaurant",
    merchant_city: "Bangkok",
    merchant_country: "TH",
    mcc_code: "5812",
    mcc_description: "Eating Places/Restaurants",
    transaction_type: "PURCHASE",
    authorization_code: "AUTH007",
    reference_number: "REF-007",
    policy_result: "AUTO_APPROVED",
    policy_reason: "Amount within restaurant threshold 3,000",
    processing_status: "PROCESSED",
    created_at: "2026-02-23T13:00:00Z"
  },
  {
    id: "bt-008",
    file_id: "file-002",
    transaction_id: "TXN-2026022808",
    cardholder_employee_id: "EMP003",
    cardholder_name: "Nattapong Kaewkla",
    transaction_date: "2026-02-22",
    posting_date: "2026-02-23",
    billing_amount: 1800,
    billing_currency: "THB",
    merchant_name: "PTT Station Sukhumvit",
    merchant_city: "Bangkok",
    merchant_country: "TH",
    mcc_code: "5541",
    mcc_description: "Service Stations",
    transaction_type: "PURCHASE",
    authorization_code: "AUTH008",
    reference_number: "REF-008",
    policy_result: "AUTO_APPROVED",
    policy_reason: "Amount within fuel threshold 2,000",
    processing_status: "PROCESSED",
    created_at: "2026-02-23T13:00:00Z"
  }
]);

// src/lib/mcp/tools/list-card-transactions.ts
var list_card_transactions_default = defineTool2({
  name: "list_card_transactions",
  title: "List card transactions",
  description: "List and search sample corporate card transactions by merchant, cardholder or ID.",
  inputSchema: {
    query: z.string().optional().describe("Text to match against merchant, cardholder or transaction ID."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, limit }, ctx) => {
    requireAuth(ctx);
    const rows = mockBankTransactions.filter(
      (t) => matches([t.transaction_id, t.merchant_name, t.cardholder_name, t.cardholder_employee_id], query)
    );
    return jsonResult(`${rows.length} transaction(s)`, rows.slice(0, limit ?? 50));
  }
});

// src/lib/mcp/tools/list-claims.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@3.0.5";
import { z as z2 } from "npm:zod@^4.6.5";

// src/lib/mock-data.ts
var mockClaims = rebaseMockDates([
  {
    id: "c1",
    claimNo: "TXN20250129001",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Taxicabs and Limousines",
    merchantName: "GRAB TAXI",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 1500,
    totalVat: 0,
    status: "Pending Invoice",
    createdDate: "2026-02-28",
    submittedDate: null,
    lines: [],
    approvalHistory: [],
    comments: []
  },
  {
    id: "c2",
    claimNo: "TXN20250129002",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Hotels and Motels",
    merchantName: "MARRIOTT HOTEL BKK",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 3500,
    totalVat: 0,
    status: "Pending Invoice",
    createdDate: "2026-02-28",
    submittedDate: null,
    lines: [],
    approvalHistory: [],
    comments: []
  },
  {
    id: "c3",
    claimNo: "TXN20250129003",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Service Stations",
    merchantName: "PTT GAS STATION",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 850,
    totalVat: 0,
    status: "Pending Invoice",
    createdDate: "2026-02-28",
    submittedDate: null,
    lines: [],
    approvalHistory: [],
    comments: []
  },
  {
    id: "c4",
    claimNo: "TXN20250129004",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Eating Places and Restaurants",
    merchantName: "SOMTUM RESTAURANT",
    currency: "THB",
    paymentMethod: "Cash",
    totalAmount: 1250,
    totalVat: 0,
    status: "Pending Invoice",
    createdDate: "2026-02-28",
    submittedDate: null,
    lines: [],
    approvalHistory: [],
    comments: []
  },
  {
    id: "c5",
    claimNo: "TXN20250129005",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Airlines",
    merchantName: "THAI AIRWAYS",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 15e3,
    totalVat: 0,
    status: "Pending Invoice",
    createdDate: "2026-02-28",
    submittedDate: null,
    lines: [],
    approvalHistory: [],
    comments: []
  },
  {
    id: "r1",
    claimNo: "TXN20260227021",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Amusement Parks",
    merchantName: "Siam Amazing Park",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 7900,
    totalVat: 0,
    status: "Auto Reject",
    createdDate: "2026-02-27",
    submittedDate: "2026-02-27",
    lines: [],
    approvalHistory: [],
    comments: []
  },
  {
    id: "r2",
    claimNo: "TXN20260227002",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Tourist Attractions",
    merchantName: "Tiger Kingdom",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 4500,
    totalVat: 0,
    status: "Auto Reject",
    createdDate: "2026-02-27",
    submittedDate: "2026-02-27",
    lines: [],
    approvalHistory: [],
    comments: []
  },
  {
    id: "r3",
    claimNo: "TXN20260227053",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Dance Halls",
    merchantName: "The Street",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 2500,
    totalVat: 0,
    status: "Auto Reject",
    createdDate: "2026-02-27",
    submittedDate: "2026-02-27",
    lines: [],
    approvalHistory: [],
    comments: []
  },
  {
    id: "r4",
    claimNo: "TXN20260227114",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Drinking Places (Bars)",
    merchantName: "The Nine",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 1250,
    totalVat: 0,
    status: "Reject",
    createdDate: "2026-02-27",
    submittedDate: "2026-02-27",
    lines: [],
    approvalHistory: [],
    comments: []
  },
  {
    id: "r5",
    claimNo: "TXN20260227025",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Sporting and Recreational Camps",
    merchantName: "Stone Hill Golf Club",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 55e3,
    totalVat: 0,
    status: "Final Rejected",
    createdDate: "2026-02-27",
    submittedDate: "2026-02-27",
    lines: [],
    approvalHistory: [],
    comments: []
  },
  {
    id: "a1",
    claimNo: "TXN20260227071",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Grocery Stores",
    merchantName: "Top",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 799,
    totalVat: 0,
    status: "Auto Approved",
    createdDate: "2026-02-27",
    submittedDate: "2026-02-27",
    lines: [],
    approvalHistory: [],
    comments: []
  },
  {
    id: "a2",
    claimNo: "TXN20260227078",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Fast Food Restaurants",
    merchantName: "KFC",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 279,
    totalVat: 0,
    status: "Auto Approved",
    createdDate: "2026-02-27",
    submittedDate: "2026-02-27",
    lines: [],
    approvalHistory: [],
    comments: []
  },
  {
    id: "a3",
    claimNo: "TXN20260227013",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Eating Places and Restaurants",
    merchantName: "Suki Teenoi",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 499,
    totalVat: 0,
    status: "Auto Approved",
    createdDate: "2026-02-27",
    submittedDate: "2026-02-27",
    lines: [],
    approvalHistory: [],
    comments: []
  },
  {
    id: "a4",
    claimNo: "TXN20260227124",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Car Rental Agencies",
    merchantName: "Good Car Service",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 3e3,
    totalVat: 0,
    status: "Manager Approved",
    createdDate: "2026-02-27",
    submittedDate: "2026-02-27",
    lines: [],
    approvalHistory: [],
    comments: []
  },
  {
    id: "a5",
    claimNo: "TXN20260227065",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Hospitals",
    merchantName: "Rama 9 Hospital",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 2500,
    totalVat: 0,
    status: "Manager Approved",
    createdDate: "2026-02-27",
    submittedDate: "2026-02-27",
    lines: [],
    approvalHistory: [],
    comments: []
  },
  {
    id: "c6",
    claimNo: "TXN20250128001",
    requesterId: "u3",
    requesterName: "Wichai Charoen",
    company: "ABC Co., Ltd.",
    branch: "Chiang Mai",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-ENG-01",
    purpose: "Taxi to client site",
    merchantName: "GRAB TAXI",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 1850,
    totalVat: 0,
    status: "Pending Invoice",
    createdDate: "2026-02-25",
    submittedDate: "2026-02-26",
    lines: [],
    approvalHistory: [{ stepNo: 1, approverId: "u1", approverName: "Somchai Jaidee", action: "Pending", comment: "", actionDate: null }],
    comments: []
  },
  {
    id: "c7",
    claimNo: "TXN20250128002",
    requesterId: "u2",
    requesterName: "Somying Kaewsai",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Business dinner with client",
    merchantName: "BANYAN TREE RESTAURANT",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 8500,
    totalVat: 595,
    status: "Pending Invoice",
    createdDate: "2026-02-24",
    submittedDate: "2026-02-25",
    lines: [],
    approvalHistory: [{ stepNo: 1, approverId: "u1", approverName: "Somchai Jaidee", action: "Pending", comment: "", actionDate: null }],
    comments: []
  },
  {
    id: "c8",
    claimNo: "TXN20250127001",
    requesterId: "u3",
    requesterName: "Wichai Charoen",
    company: "ABC Co., Ltd.",
    branch: "Chiang Mai",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-ENG-01",
    purpose: "Flight to Bangkok for meeting",
    merchantName: "THAI AIRWAYS",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 12500,
    totalVat: 0,
    status: "Pending Invoice",
    createdDate: "2026-02-23",
    submittedDate: "2026-02-24",
    lines: [],
    approvalHistory: [{ stepNo: 1, approverId: "u1", approverName: "Somchai Jaidee", action: "Pending", comment: "", actionDate: null }],
    comments: []
  },
  {
    id: "c9",
    claimNo: "TXN20250127002",
    requesterId: "u2",
    requesterName: "Somying Kaewsai",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Hotel for regional meeting",
    merchantName: "NOVOTEL BANGKOK",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 4200,
    totalVat: 294,
    status: "Pending Invoice",
    createdDate: "2026-02-22",
    submittedDate: "2026-02-23",
    lines: [],
    approvalHistory: [{ stepNo: 1, approverId: "u1", approverName: "Somchai Jaidee", action: "Pending", comment: "", actionDate: null }],
    comments: []
  },
  {
    id: "c10",
    claimNo: "TXN20250126001",
    requesterId: "u3",
    requesterName: "Wichai Charoen",
    company: "ABC Co., Ltd.",
    branch: "Chiang Mai",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-ENG-01",
    purpose: "Office supplies for project",
    merchantName: "OfficeMate",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 3200,
    totalVat: 224,
    status: "Pending Invoice",
    createdDate: "2026-02-21",
    submittedDate: "2026-02-22",
    lines: [],
    approvalHistory: [{ stepNo: 1, approverId: "u1", approverName: "Somchai Jaidee", action: "Pending", comment: "", actionDate: null }],
    comments: []
  },
  // Returned For Info claims (April 2026)
  {
    id: "rfi1",
    claimNo: "Transaction20260415001",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Taxicabs and Limousines",
    merchantName: "GRAB TAXI",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 1500,
    totalVat: 0,
    status: "Returned For Info",
    createdDate: "2026-04-01",
    submittedDate: "2026-04-01",
    corpTxnDocumentStatus: "PENDING_DOCUMENTS",
    lines: [],
    approvalHistory: [],
    comments: []
  },
  {
    id: "rfi2",
    claimNo: "Transaction20260415002",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Hotels and Motels",
    merchantName: "MARRIOTT HOTEL BKK",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 3500,
    totalVat: 0,
    status: "Returned For Info",
    createdDate: "2026-04-02",
    submittedDate: "2026-04-02",
    corpTxnDocumentStatus: "PENDING_DOCUMENTS",
    lines: [],
    approvalHistory: [],
    comments: []
  },
  {
    id: "rfi3",
    claimNo: "Transaction20260415003",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Eating Places and Restaurants",
    merchantName: "STARBUCKS",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 850,
    totalVat: 0,
    status: "Returned For Info",
    createdDate: "2026-04-03",
    submittedDate: "2026-04-03",
    corpTxnDocumentStatus: "VALIDATED",
    lines: [],
    approvalHistory: [],
    comments: []
  },
  {
    id: "rfi4",
    claimNo: "Transaction20260415004",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Amusement Parks",
    merchantName: "Siam Amazing Park",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 7900,
    totalVat: 0,
    status: "Returned For Info",
    createdDate: "2026-04-04",
    submittedDate: "2026-04-04",
    corpTxnDocumentStatus: "PENDING_DOCUMENTS",
    lines: [],
    approvalHistory: [],
    comments: []
  },
  {
    id: "rfi5",
    claimNo: "Transaction20260415005",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Airlines",
    merchantName: "THAI AIRWAYS",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 15e3,
    totalVat: 0,
    status: "Returned For Info",
    createdDate: "2026-04-05",
    submittedDate: "2026-04-05",
    corpTxnDocumentStatus: "SUBMITTED",
    lines: [],
    approvalHistory: [],
    comments: []
  },
  {
    id: "rfi6",
    claimNo: "Transaction20260415006",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Department Stores",
    merchantName: "CENTRAL DEPARTMENT",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 2300,
    totalVat: 0,
    status: "Returned For Info",
    createdDate: "2026-04-06",
    submittedDate: "2026-04-06",
    corpTxnDocumentStatus: "PENDING_DOCUMENTS",
    lines: [],
    approvalHistory: [],
    comments: []
  },
  {
    id: "rfi7",
    claimNo: "Transaction20260415007",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Fast Food Restaurants",
    merchantName: "KFC",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 279,
    totalVat: 0,
    status: "Returned For Info",
    createdDate: "2026-04-07",
    submittedDate: "2026-04-07",
    corpTxnDocumentStatus: "PENDING_DOCUMENTS",
    lines: [],
    approvalHistory: [],
    comments: []
  },
  // Pending Approval claims (for Approval Inbox)
  {
    id: "pa1",
    claimNo: "TXN20260301001",
    requesterId: "u6",
    requesterName: "Somying Prasertsuk",
    company: "CP Axtra Co., Ltd.",
    branch: "Bangkok",
    department: "Commercial \u2014 HoReCa",
    costCenter: "CC-COM-01",
    purpose: "Airline \u2014 Domestic (Bangkok \u2192 Chiang Mai, Sales Visit)",
    merchantName: "THAI AIRWAYS",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 8500,
    totalVat: 0,
    status: "Pending Approval",
    createdDate: "2026-03-01",
    submittedDate: "2026-03-01",
    lines: [],
    approvalHistory: [{ stepNo: 1, approverId: "u1", approverName: "Somchai Jaidee", action: "Pending", comment: "", actionDate: null }],
    comments: []
  },
  {
    id: "pa2",
    claimNo: "TXN20260301002",
    requesterId: "u7",
    requesterName: "Nattapon Wichai",
    company: "CP Axtra Co., Ltd.",
    branch: "Bangkok",
    department: "Operations \u2014 Supply Chain",
    costCenter: "CC-OPS-01",
    purpose: "Car Rental (3 days, site inspection Rayong)",
    merchantName: "BUDGET CAR RENTAL",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 12e3,
    totalVat: 0,
    status: "Pending Approval",
    createdDate: "2026-03-02",
    submittedDate: "2026-03-02",
    lines: [],
    approvalHistory: [{ stepNo: 1, approverId: "u1", approverName: "Somchai Jaidee", action: "Pending", comment: "", actionDate: null }],
    comments: []
  },
  {
    id: "pa3",
    claimNo: "TXN20260305001",
    requesterId: "u8",
    requesterName: "Kannika Thongsuk",
    company: "CP Axtra Co., Ltd.",
    branch: "Bangkok",
    department: "Finance \u2014 Accounting",
    costCenter: "CC-FIN-01",
    purpose: "Airline \u2014 Overseas (Bangkok \u2192 Singapore, Regional Meeting)",
    merchantName: "SINGAPORE AIRLINES",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 42500,
    totalVat: 0,
    status: "Pending Approval",
    createdDate: "2026-03-05",
    submittedDate: "2026-03-05",
    lines: [],
    approvalHistory: [{ stepNo: 1, approverId: "u1", approverName: "Somchai Jaidee", action: "Pending", comment: "", actionDate: null }],
    comments: []
  },
  {
    id: "pa4",
    claimNo: "TXN20260310001",
    requesterId: "u6",
    requesterName: "Somying Prasertsuk",
    company: "CP Axtra Co., Ltd.",
    branch: "Bangkok",
    department: "Commercial \u2014 HoReCa",
    costCenter: "CC-COM-01",
    purpose: "Car Rental (2 days, customer event Pattaya)",
    merchantName: "AVIS RENT A CAR",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 9200,
    totalVat: 0,
    status: "Pending Approval",
    createdDate: "2026-03-10",
    submittedDate: "2026-03-10",
    lines: [],
    approvalHistory: [{ stepNo: 1, approverId: "u1", approverName: "Somchai Jaidee", action: "Pending", comment: "", actionDate: null }],
    comments: []
  },
  {
    id: "CLM-TEST-REJECT-001",
    claimNo: "CLM-2026-TEST-001",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "SINGAPORE AIRLINES",
    merchantName: "SINGAPORE AIRLINES",
    currency: "THB",
    paymentMethod: "Corporate Card",
    expenseTypeId: "et-2",
    subExpenseTypeId: "set-8",
    vatTypeId: "claim_100",
    glAccountId: "gl-9",
    totalAmount: 18224,
    totalVat: 0,
    status: "Reject",
    createdDate: "2026-05-10",
    submittedDate: "2026-05-10",
    lines: [],
    approvalHistory: [],
    comments: [],
    returnSource: "MANAGER_REJECT",
    returnedByUserId: "u2",
    returnedAt: "2026-05-11T16:22:00Z",
    returnMessage: "Travel approval letter doesn't match the trip dates on the booking. Please attach the corrected approval and resubmit.",
    resubmitCountMgr: 0,
    documentChecklistOverride: {
      required: [{ id: "dt-eticket-test", documentName: "E-Ticket / Flight ticket", isSupportDocument: false }],
      optional: [{ id: "dt-travel-insurance-test", documentName: "Travel Insurance Certificate", isSupportDocument: true }]
    }
  },
  {
    id: "CLM-TEST-RFI-001",
    claimNo: "CLM-2026-TEST-002",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Cloud Services",
    merchantName: "AMAZON WEB SERVICES",
    currency: "THB",
    paymentMethod: "Corporate Card",
    totalAmount: 5420.5,
    totalVat: 0,
    status: "Returned For Info",
    createdDate: "2026-05-10",
    submittedDate: "2026-05-10",
    lines: [],
    approvalHistory: [],
    comments: [],
    returnSource: "MANAGER_RFI",
    returnedByUserId: "u2",
    returnedAt: "2026-05-11T17:45:00Z",
    returnMessage: "Can you justify this as a business expense and attach pre-approval from Director Y? What project does this AWS bill cover?"
  },
  {
    id: "CLM-BIZ-DEMO-RFI-001",
    claimNo: "CLM-2026-TEST-002",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Travel to train End User at Chiang Mai from 19 May 2026 to 20 May 2026",
    merchantName: "Thai Airways",
    currency: "THB",
    paymentMethod: "Corporate Card",
    expenseTypeId: "et-1",
    subExpenseTypeId: "set-5",
    vatTypeId: "claim_100",
    glAccountId: "gl-1",
    totalAmount: 5420.5,
    totalVat: 0,
    status: "Returned For Info",
    createdDate: "2026-05-10",
    submittedDate: "2026-05-10",
    lines: [],
    approvalHistory: [],
    comments: [],
    cardholderNote: "Add Boarding Pass for reference",
    returnSource: "MANAGER_RFI",
    returnedByUserId: "u2",
    returnedAt: "2026-05-11T17:45:00Z",
    returnMessage: "Can you justify this as a business expense and attach pre-approval from Director Y? What project does this AWS bill cover?"
  },
  {
    id: "CLM-BIZ-DEMO-RFI-002",
    claimNo: "CLM-BIZ-DEMO-RFI-002",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Travel to train End User at Chiang Mai from 19 May 2026 to 20 May 2026",
    merchantName: "Thai Airways",
    currency: "THB",
    paymentMethod: "Corporate Card",
    expenseTypeId: "et-2",
    subExpenseTypeId: "set-8",
    vatTypeId: "claim_100",
    glAccountId: "gl-9",
    totalAmount: 5420.5,
    totalVat: 0,
    status: "Returned For Info",
    createdDate: "2026-05-10",
    submittedDate: "2026-05-10",
    lines: [],
    approvalHistory: [],
    comments: [],
    cardholderNote: "Add Boarding Pass for reference",
    returnSource: "MANAGER_RFI",
    returnedByUserId: "u2",
    returnedAt: "2026-05-11T17:45:00Z",
    returnMessage: "Can you justify this as a business expense and attach pre-approval from Director Y? What project does this AWS bill cover?"
  },
  {
    id: "CLM-TEST-FIN-001",
    claimNo: "CLM-2026-TEST-003",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Drinking Places (Bars)",
    merchantName: "IRON FAIRIES",
    currency: "THB",
    paymentMethod: "Corporate Card",
    expenseTypeId: "et-1",
    subExpenseTypeId: "set-7",
    vatTypeId: "claim_100",
    glAccountId: "gl-11",
    totalAmount: 3200,
    totalVat: 0,
    status: "Returned By Finance",
    createdDate: "2026-05-11",
    submittedDate: "2026-05-11",
    lines: [],
    approvalHistory: [],
    comments: [],
    returnSource: "FINANCE_RETURN",
    returnedByUserId: "u7",
    returnedAt: "2026-05-12T09:10:00Z",
    returnMessage: "Buyer Tax ID on the Full Tax Invoice is incorrect for CPAxtra \u2014 it shows '01095...' but our entity is '01075...'. Please request a corrected invoice from the vendor."
  },
  {
    id: "CLM-TEST-FINAL-001",
    claimNo: "CLM-2026-TEST-004",
    requesterId: "u1",
    requesterName: "Somchai Jaidee",
    company: "ABC Co., Ltd.",
    branch: "Bangkok",
    department: "9993010460 Finance and Accounting",
    costCenter: "CC-SALES-01",
    purpose: "Purchased office supplies for business use.",
    merchantName: "B2S",
    currency: "THB",
    paymentMethod: "Corporate Card",
    expenseTypeId: "et-4",
    subExpenseTypeId: "set-13",
    vatTypeId: "claim_100",
    glAccountId: "gl-10",
    totalAmount: 39590,
    totalVat: 0,
    status: "Final Rejected",
    createdDate: "2026-05-09",
    submittedDate: "2026-05-09",
    lines: [],
    approvalHistory: [],
    comments: [],
    returnSource: "MANAGER_REJECT",
    returnedByUserId: "u2",
    returnedAt: "2026-05-12T11:00:00Z",
    returnMessage: "This claim cannot be reimbursed as it does not meet the conditions of the corporate credit card usage policy.",
    resubmitCountMgr: 1,
    cardholderNote: "Bought a notebook for client meeting prep. Vendor refused to issue a corrected invoice."
  }
]);
var mockBankTransactions2 = rebaseMockDates([
  { id: "TXN-001", txnDate: "2025-02-01", amount: 15200, merchant: "Thai Airways", cardholderName: "Somchai Jaidee", reference: "REF-001", status: "Matched", linkedClaimId: "c1" },
  { id: "TXN-002", txnDate: "2025-02-03", amount: 850, merchant: "Starbucks Siam", cardholderName: "Somying Kaewsai", reference: "REF-002", status: "Unmatched", linkedClaimId: null },
  { id: "TXN-003", txnDate: "2025-02-05", amount: 12e3, merchant: "Amazon Web Services", cardholderName: "Wichai Charoen", reference: "REF-003", status: "Partially Matched", linkedClaimId: "c6" },
  { id: "TXN-004", txnDate: "2025-02-06", amount: 320, merchant: "Grab Transport", cardholderName: "Napa Jamsai", reference: "REF-004", status: "Exception", linkedClaimId: null }
]);

// src/lib/mcp/tools/list-claims.ts
var list_claims_default = defineTool3({
  name: "list_expense_claims",
  title: "List expense claims",
  description: "List sample expense claims with status and totals; optionally filter by text or status.",
  inputSchema: {
    query: z2.string().optional().describe("Text to match against claim no., requester or purpose."),
    status: z2.string().optional().describe("Exact claim status to filter by.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, status }, ctx) => {
    requireAuth(ctx);
    const rows = mockClaims.filter((c) => (!status || c.status === status) && matches([c.id, c.claimNo, c.requesterName, c.purpose], query)).map((c) => ({
      id: c.id,
      claimNo: c.claimNo,
      requester: c.requesterName,
      department: c.department,
      purpose: c.purpose,
      status: c.status,
      totalAmount: c.totalAmount,
      currency: c.currency,
      createdDate: c.createdDate,
      lineCount: c.lines.length
    }));
    return jsonResult(`${rows.length} claim(s)`, rows);
  }
});

// src/lib/mcp/tools/get-claim.ts
import { defineTool as defineTool4, ToolError } from "npm:@lovable.dev/mcp-js@3.0.5";
import { z as z3 } from "npm:zod@^4.6.5";
var get_claim_default = defineTool4({
  name: "get_expense_claim",
  title: "Get expense claim",
  description: "Get full details of one sample expense claim, including lines and approval steps.",
  inputSchema: { id: z3.string().min(1).describe("Claim ID or claim number.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }, ctx) => {
    requireAuth(ctx);
    const claim = mockClaims.find((c) => c.id === id || c.claimNo === id);
    if (!claim) throw new ToolError(`Claim ${id} not found`);
    return jsonResult(`Claim ${claim.claimNo}`, claim);
  }
});

// src/lib/mcp/tools/list-cards.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@3.0.5";
import { z as z4 } from "npm:zod@^4.6.5";

// src/lib/card-master-mock-data.ts
function mmYY(d) {
  return `${String(d.getMonth() + 1).padStart(2, "0")}/${String(d.getFullYear() % 100).padStart(2, "0")}`;
}
var soon = /* @__PURE__ */ new Date();
soon.setDate(soon.getDate() + 45);
var CARD_MASTER_ROWS = [
  {
    cardId: "FL-2026-00427",
    kind: "fleet",
    bankTh: "\u0E01\u0E2A\u0E34\u0E01\u0E23\u0E44\u0E17\u0E22",
    last4: "8841",
    plateNo: "70-8814",
    creditLimit: 2e5,
    expiry: "08/29",
    status: "Created",
    company: "Makro"
  },
  {
    cardId: "FL-2026-00431",
    kind: "fleet",
    bankTh: "\u0E01\u0E2A\u0E34\u0E01\u0E23\u0E44\u0E17\u0E22",
    last4: "9012",
    plateNo: "82-1150",
    creditLimit: 15e4,
    expiry: "09/29",
    status: "Created",
    company: "Makro"
  },
  {
    cardId: "FL-2026-00419",
    kind: "fleet",
    bankTh: "\u0E01\u0E23\u0E38\u0E07\u0E28\u0E23\u0E35",
    last4: "7745",
    plateNo: "\u0E01\u0E02-5678",
    creditLimit: 12e4,
    expiry: "07/29",
    status: "Handed Over",
    company: "Makro"
  },
  {
    cardId: "FL-2026-00405",
    kind: "fleet",
    bankTh: "\u0E01\u0E2A\u0E34\u0E01\u0E23\u0E44\u0E17\u0E22",
    last4: "6623",
    plateNo: "3\u0E02\u0E04-9911",
    creditLimit: 1e5,
    expiry: "10/29",
    status: "Received",
    company: "Makro"
  },
  {
    cardId: "CC-2026-35775",
    kind: "corporate",
    bankTh: "\u0E01\u0E23\u0E38\u0E07\u0E28\u0E23\u0E35",
    last4: "3577",
    cardholderName: "Somchai Jaidee",
    employeeId: "EMP-10021",
    creditLimit: 5e5,
    expiry: "08/29",
    status: "Active",
    company: "CP AXTRA PCL"
  },
  {
    cardId: "FL-2026-00412",
    kind: "fleet",
    fuelBrand: "PTT",
    bankTh: "\u0E01\u0E2A\u0E34\u0E01\u0E23\u0E44\u0E17\u0E22",
    last4: "8841",
    plateNo: "70-8814",
    creditLimit: 2e5,
    expiry: "08/29",
    status: "Active",
    company: "Makro"
  },
  {
    cardId: "CC-2026-31208",
    kind: "corporate",
    bankTh: "\u0E01\u0E2A\u0E34\u0E01\u0E23\u0E44\u0E17\u0E22",
    last4: "3120",
    cardholderName: "Thanit Boonmee",
    employeeId: "EMP-10044",
    creditLimit: 3e5,
    expiry: "11/28",
    status: "Active",
    company: "Lotus's"
  },
  {
    cardId: "CC-2026-29944",
    kind: "corporate",
    bankTh: "\u0E01\u0E23\u0E38\u0E07\u0E28\u0E23\u0E35",
    last4: "2994",
    cardholderName: "Naruemon Srisuk",
    employeeId: "EMP-10077",
    creditLimit: 15e4,
    expiry: mmYY(soon),
    status: "Active",
    company: "CP AXTRA PCL"
  },
  {
    cardId: "FL-2026-00398",
    kind: "fleet",
    fuelBrand: "Bangchak",
    bankTh: "\u0E01\u0E2A\u0E34\u0E01\u0E23\u0E44\u0E17\u0E22",
    last4: "5512",
    plateNo: "82-1145",
    creditLimit: 12e4,
    expiry: "03/29",
    status: "Suspended",
    company: "Makro"
  },
  {
    cardId: "CC-2025-88120",
    kind: "corporate",
    bankTh: "\u0E01\u0E23\u0E38\u0E07\u0E28\u0E23\u0E35",
    last4: "8812",
    cardholderName: "Pornthip Wattana",
    employeeId: "EMP-10102",
    creditLimit: 25e4,
    expiry: "01/25",
    status: "Expired",
    company: "Lotus's"
  },
  {
    cardId: "CC-2025-77341",
    kind: "corporate",
    bankTh: "\u0E01\u0E2A\u0E34\u0E01\u0E23\u0E44\u0E17\u0E22",
    last4: "7734",
    cardholderName: "Anucha Meesuk",
    employeeId: "EMP-10118",
    creditLimit: 4e5,
    expiry: "06/28",
    status: "Cancelled",
    company: "CP AXTRA PCL"
  },
  {
    cardId: "FL-2025-00317",
    kind: "fleet",
    fuelBrand: "PTT",
    bankTh: "\u0E01\u0E23\u0E38\u0E07\u0E28\u0E23\u0E35",
    last4: "1290",
    plateNo: "\u0E01\u0E02-1234",
    creditLimit: 18e4,
    expiry: "09/28",
    status: "Active",
    company: "Makro"
  },
  {
    cardId: "CC-2025-66220",
    kind: "corporate",
    bankTh: "\u0E01\u0E2A\u0E34\u0E01\u0E23\u0E44\u0E17\u0E22",
    last4: "6622",
    cardholderName: "Kanya Phongsri",
    employeeId: "EMP-10133",
    creditLimit: 6e5,
    expiry: "12/29",
    status: "Active",
    company: "Lotus's"
  },
  {
    cardId: "FL-2025-00288",
    kind: "fleet",
    fuelBrand: "Shell",
    bankTh: "\u0E01\u0E23\u0E38\u0E07\u0E28\u0E23\u0E35",
    last4: "4408",
    plateNo: "5\u0E01\u0E01-9921",
    creditLimit: 9e4,
    expiry: "07/28",
    status: "Suspended",
    company: "Makro"
  },
  {
    cardId: "CC-2025-55010",
    kind: "corporate",
    bankTh: "\u0E01\u0E2A\u0E34\u0E01\u0E23\u0E44\u0E17\u0E22",
    last4: "5501",
    cardholderName: "Weerachai Tanaka",
    employeeId: "EMP-10150",
    creditLimit: 35e4,
    expiry: "05/29",
    status: "Active",
    company: "CP AXTRA PCL"
  },
  {
    cardId: "FL-2025-00201",
    kind: "fleet",
    fuelBrand: "Bangchak",
    bankTh: "\u0E01\u0E23\u0E38\u0E07\u0E28\u0E23\u0E35",
    last4: "2011",
    plateNo: "3\u0E02\u0E04-4477",
    creditLimit: 1e5,
    expiry: "10/28",
    status: "Active",
    company: "Lotus's"
  }
];

// src/lib/mcp/tools/list-cards.ts
var list_cards_default = defineTool5({
  name: "list_cards",
  title: "List cards",
  description: "List sample Card Management records (Corporate Credit and Fleet Cards), masked to last 4 digits.",
  inputSchema: {
    cardType: z4.enum(["corporate", "fleet"]).optional().describe("Filter by card type."),
    query: z4.string().optional().describe("Text to match against card ID or cardholder.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ cardType, query }, ctx) => {
    requireAuth(ctx);
    const rows = CARD_MASTER_ROWS.filter((r) => (!cardType || r.kind === cardType) && matches([r.cardId, r.cardholderName, r.employeeId], query)).map((r) => ({
      cardId: r.cardId,
      cardType: r.kind,
      bank: r.bankTh,
      last4: r.last4,
      cardholder: r.cardholderName ?? "Unassigned",
      employeeId: r.employeeId ?? null,
      creditLimit: r.creditLimit,
      expiry: r.expiry,
      status: r.status,
      company: r.company
    }));
    return jsonResult(`${rows.length} card(s)`, rows);
  }
});

// src/lib/mcp/tools/list-policies.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@3.0.5";
import { z as z5 } from "npm:zod@^4.6.5";

// src/lib/expense-type-config.ts
var EXPENSE_TYPE_CONFIG = [
  // ── TRANSPORTATION — DOMESTIC ──────────────────────────────
  {
    level1: "Transportation \u2014 Domestic",
    level2: "Taxi / Grab",
    policyRule: "Auto Approve",
    threshold: 1500,
    currency: "THB",
    glCode: "5300-002",
    requiredDocs: [
      { id: "receipt", label: "\u0E43\u0E1A\u0E40\u0E2A\u0E23\u0E47\u0E08\u0E23\u0E31\u0E1A\u0E40\u0E07\u0E34\u0E19 / Receipt", required: true },
      { id: "claim_form", label: "Travelling Expenses Claim Form", required: true }
    ],
    optionalDocs: [
      { id: "memo", label: "Memo / Business Purpose (\u0E01\u0E23\u0E13\u0E35\u0E40\u0E01\u0E34\u0E19 Threshold)", required: false }
    ]
  },
  {
    level1: "Transportation \u2014 Domestic",
    level2: "BTS / MRT / Public Transit",
    policyRule: "Auto Approve",
    threshold: 500,
    currency: "THB",
    glCode: "5300-002",
    requiredDocs: [
      { id: "claim_form", label: "Travelling Expenses Claim Form", required: true }
    ],
    optionalDocs: [
      { id: "receipt", label: "\u0E43\u0E1A\u0E40\u0E2A\u0E23\u0E47\u0E08 / \u0E15\u0E31\u0E4B\u0E27 (\u0E16\u0E49\u0E32\u0E21\u0E35 \u2014 \u0E44\u0E21\u0E48\u0E1A\u0E31\u0E07\u0E04\u0E31\u0E1A \u2264200 THB)", required: false }
    ]
  },
  {
    level1: "Transportation \u2014 Domestic",
    level2: "Train / Inter-city Bus",
    policyRule: "Auto Approve",
    threshold: 1e3,
    currency: "THB",
    glCode: "5300-002",
    requiredDocs: [
      { id: "ticket", label: "\u0E15\u0E31\u0E4B\u0E27\u0E23\u0E16\u0E44\u0E1F / \u0E23\u0E16\u0E17\u0E31\u0E27\u0E23\u0E4C", required: true },
      { id: "claim_form", label: "Travelling Expenses Claim Form", required: true }
    ],
    optionalDocs: []
  },
  {
    level1: "Transportation \u2014 Domestic",
    level2: "Personal Car \u2014 Mileage",
    policyRule: "Auto Approve",
    threshold: 2e3,
    currency: "THB",
    glCode: "5300-004",
    requiredDocs: [
      { id: "receipt_fuel", label: "\u0E43\u0E1A\u0E40\u0E2A\u0E23\u0E47\u0E08\u0E19\u0E49\u0E33\u0E21\u0E31\u0E19 (\u0E1E\u0E23\u0E49\u0E2D\u0E21\u0E23\u0E30\u0E1A\u0E38\u0E17\u0E30\u0E40\u0E1A\u0E35\u0E22\u0E19\u0E23\u0E16)", required: true },
      { id: "trip_detail", label: "\u0E23\u0E32\u0E22\u0E25\u0E30\u0E40\u0E2D\u0E35\u0E22\u0E14\u0E01\u0E32\u0E23\u0E40\u0E14\u0E34\u0E19\u0E17\u0E32\u0E07 (\u0E15\u0E49\u0E19\u0E17\u0E32\u0E07\u2013\u0E1B\u0E25\u0E32\u0E22\u0E17\u0E32\u0E07\u2013\u0E01\u0E34\u0E42\u0E25\u0E40\u0E21\u0E15\u0E23)", required: true },
      { id: "insurance_proof", label: "\u0E2B\u0E25\u0E31\u0E01\u0E10\u0E32\u0E19\u0E1B\u0E23\u0E30\u0E01\u0E31\u0E19\u0E20\u0E31\u0E22 \u0E1E.\u0E23.\u0E1A. + \u0E1B\u0E23\u0E30\u0E01\u0E31\u0E19\u0E2A\u0E21\u0E31\u0E04\u0E23\u0E43\u0E08", required: true },
      { id: "claim_form", label: "Travelling Expenses Claim Form", required: true }
    ],
    optionalDocs: []
  },
  {
    level1: "Transportation \u2014 Domestic",
    level2: "EV Car \u2014 Mileage",
    policyRule: "Auto Approve",
    threshold: 3e3,
    currency: "THB",
    glCode: "5300-004",
    requiredDocs: [
      { id: "ev_receipt", label: "\u0E43\u0E1A\u0E40\u0E2A\u0E23\u0E47\u0E08\u0E0A\u0E32\u0E23\u0E4C\u0E08\u0E44\u0E1F EV (EV Charging Receipt)", required: true },
      { id: "trip_detail", label: "\u0E23\u0E32\u0E22\u0E25\u0E30\u0E40\u0E2D\u0E35\u0E22\u0E14\u0E01\u0E32\u0E23\u0E40\u0E14\u0E34\u0E19\u0E17\u0E32\u0E07 (\u0E15\u0E49\u0E19\u0E17\u0E32\u0E07\u2013\u0E1B\u0E25\u0E32\u0E22\u0E17\u0E32\u0E07\u2013\u0E01\u0E34\u0E42\u0E25\u0E40\u0E21\u0E15\u0E23)", required: true },
      { id: "claim_form", label: "Travelling Expenses Claim Form", required: true }
    ],
    optionalDocs: [
      { id: "ev_allowance_note", label: "\u0E2B\u0E21\u0E32\u0E22\u0E40\u0E2B\u0E15\u0E38: EV Allowance 3,000 THB/\u0E40\u0E14\u0E37\u0E2D\u0E19 (HR-CB-001-2567)", required: false }
    ]
  },
  {
    level1: "Transportation \u2014 Domestic",
    level2: "Toll Fees / \u0E04\u0E48\u0E32\u0E17\u0E32\u0E07\u0E14\u0E48\u0E27\u0E19",
    policyRule: "Auto Approve",
    threshold: 3500,
    currency: "THB",
    glCode: "5300-002",
    requiredDocs: [
      { id: "receipt", label: "\u0E43\u0E1A\u0E40\u0E2A\u0E23\u0E47\u0E08\u0E04\u0E48\u0E32\u0E17\u0E32\u0E07\u0E14\u0E48\u0E27\u0E19", required: true },
      { id: "claim_form", label: "Travelling Expenses Claim Form", required: true }
    ],
    optionalDocs: []
  },
  {
    level1: "Transportation \u2014 Domestic",
    level2: "Airport Parking",
    policyRule: "Auto Approve",
    threshold: 500,
    currency: "THB",
    glCode: "5300-002",
    requiredDocs: [
      { id: "receipt", label: "\u0E43\u0E1A\u0E40\u0E2A\u0E23\u0E47\u0E08\u0E04\u0E48\u0E32\u0E08\u0E2D\u0E14\u0E23\u0E16 (\u22644 \u0E27\u0E31\u0E19 / 96 \u0E0A\u0E31\u0E48\u0E27\u0E42\u0E21\u0E07)", required: true }
    ],
    optionalDocs: []
  },
  {
    level1: "Transportation \u2014 Domestic",
    level2: "Car Rental",
    policyRule: "Requires Approval",
    threshold: null,
    currency: "THB",
    glCode: "5300-003",
    requiredDocs: [
      { id: "invoice", label: "Invoice / \u0E43\u0E1A\u0E40\u0E2A\u0E23\u0E47\u0E08\u0E08\u0E32\u0E01\u0E1A\u0E23\u0E34\u0E29\u0E31\u0E17\u0E23\u0E16\u0E40\u0E0A\u0E48\u0E32", required: true },
      { id: "cga_booking", label: "\u0E2B\u0E25\u0E31\u0E01\u0E10\u0E32\u0E19\u0E01\u0E32\u0E23\u0E08\u0E2D\u0E07\u0E1C\u0E48\u0E32\u0E19 CGA Booking", required: true },
      { id: "travel_approval", label: "\u0E2B\u0E19\u0E31\u0E07\u0E2A\u0E37\u0E2D\u0E2D\u0E19\u0E38\u0E21\u0E31\u0E15\u0E34\u0E40\u0E14\u0E34\u0E19\u0E17\u0E32\u0E07 (Travel Approval)", required: true }
    ],
    optionalDocs: [
      { id: "outside_contract_approval", label: "\u0E2D\u0E19\u0E38\u0E21\u0E31\u0E15\u0E34\u0E08\u0E32\u0E01 Associate Director (\u0E01\u0E23\u0E13\u0E35\u0E19\u0E2D\u0E01\u0E2A\u0E31\u0E0D\u0E0D\u0E32)", required: false }
    ]
  },
  {
    level1: "Transportation \u2014 Domestic",
    level2: "Airline \u2014 Domestic",
    policyRule: "Requires Approval",
    threshold: null,
    currency: "THB",
    glCode: "5300-001",
    requiredDocs: [
      { id: "eticket", label: "E-Ticket / \u0E15\u0E31\u0E4B\u0E27\u0E40\u0E04\u0E23\u0E37\u0E48\u0E2D\u0E07\u0E1A\u0E34\u0E19", required: true },
      { id: "director_approval", label: "\u0E2B\u0E19\u0E31\u0E07\u0E2A\u0E37\u0E2D\u0E2D\u0E19\u0E38\u0E21\u0E31\u0E15\u0E34\u0E08\u0E32\u0E01 Director \u0E02\u0E36\u0E49\u0E19\u0E44\u0E1B (HQ) \u0E2B\u0E23\u0E37\u0E2D SGM (\u0E2A\u0E42\u0E15\u0E23\u0E4C)", required: true },
      { id: "cga_booking", label: "\u0E2B\u0E25\u0E31\u0E01\u0E10\u0E32\u0E19\u0E01\u0E32\u0E23\u0E08\u0E2D\u0E07\u0E1C\u0E48\u0E32\u0E19 Agency / CGA", required: true },
      { id: "tax_invoice", label: "\u0E43\u0E1A\u0E01\u0E33\u0E01\u0E31\u0E1A\u0E20\u0E32\u0E29\u0E35 (Tax Invoice)", required: true }
    ],
    optionalDocs: [
      { id: "boarding_pass", label: "Boarding Pass", required: false }
    ]
  },
  {
    level1: "Transportation \u2014 Domestic",
    level2: "Courier / Postage",
    policyRule: "Auto Approve",
    threshold: 500,
    currency: "THB",
    glCode: "5300-005",
    requiredDocs: [
      { id: "receipt", label: "\u0E43\u0E1A\u0E40\u0E2A\u0E23\u0E47\u0E08 Courier / \u0E43\u0E1A\u0E19\u0E33\u0E2A\u0E48\u0E07", required: true }
    ],
    optionalDocs: []
  },
  // ── TRANSPORTATION — OVERSEAS ───────────────────────────────
  {
    level1: "Transportation \u2014 Overseas",
    level2: "Airline \u2014 Overseas",
    policyRule: "Requires Approval",
    threshold: null,
    currency: "THB",
    glCode: "5300-001",
    requiredDocs: [
      { id: "eticket", label: "E-Ticket / \u0E15\u0E31\u0E4B\u0E27\u0E40\u0E04\u0E23\u0E37\u0E48\u0E2D\u0E07\u0E1A\u0E34\u0E19", required: true },
      { id: "boarding_pass", label: "Boarding Pass", required: true },
      { id: "tax_invoice", label: "\u0E43\u0E1A\u0E01\u0E33\u0E01\u0E31\u0E1A\u0E20\u0E32\u0E29\u0E35 / Invoice", required: true },
      { id: "travel_approval", label: "\u0E2B\u0E19\u0E31\u0E07\u0E2A\u0E37\u0E2D\u0E2D\u0E19\u0E38\u0E21\u0E31\u0E15\u0E34\u0E40\u0E14\u0E34\u0E19\u0E17\u0E32\u0E07\u0E15\u0E48\u0E32\u0E07\u0E1B\u0E23\u0E30\u0E40\u0E17\u0E28 (Chief Level \u0E02\u0E36\u0E49\u0E19\u0E44\u0E1B)", required: true },
      { id: "cga_booking", label: "\u0E2B\u0E25\u0E31\u0E01\u0E10\u0E32\u0E19\u0E01\u0E32\u0E23\u0E08\u0E2D\u0E07\u0E1C\u0E48\u0E32\u0E19 Agency / CGA", required: true },
      { id: "travel_insurance", label: "Travel Insurance Certificate (\u0E41\u0E08\u0E49\u0E07 HR \u0E25\u0E48\u0E27\u0E07\u0E2B\u0E19\u0E49\u0E32 \u22657 \u0E27\u0E31\u0E19)", required: true }
    ],
    optionalDocs: [
      { id: "upgrade_memo", label: "\u0E2B\u0E19\u0E31\u0E07\u0E2A\u0E37\u0E2D\u0E2D\u0E18\u0E34\u0E1A\u0E32\u0E22\u0E40\u0E2B\u0E15\u0E38\u0E1C\u0E25\u0E02\u0E2D\u0E19\u0E31\u0E48\u0E07 Business Class", required: false },
      { id: "passport_visa", label: "Passport Copy \u0E2B\u0E19\u0E49\u0E32 Visa (\u0E01\u0E23\u0E13\u0E35\u0E02\u0E2D Visa Reimbursement)", required: false }
    ]
  },
  {
    level1: "Transportation \u2014 Overseas",
    level2: "Ground Transport (Overseas)",
    policyRule: "Auto Approve",
    threshold: null,
    currency: "THB",
    glCode: "5300-002",
    requiredDocs: [
      { id: "receipt", label: "\u0E43\u0E1A\u0E40\u0E2A\u0E23\u0E47\u0E08\u0E04\u0E48\u0E32\u0E1E\u0E32\u0E2B\u0E19\u0E30\u0E43\u0E19\u0E1B\u0E23\u0E30\u0E40\u0E17\u0E28\u0E1B\u0E25\u0E32\u0E22\u0E17\u0E32\u0E07", required: true },
      { id: "perdiem_form", label: "Per Diem Claim Form (\u0E41\u0E1A\u0E1A\u0E1F\u0E2D\u0E23\u0E4C\u0E21\u0E40\u0E1A\u0E35\u0E49\u0E22\u0E40\u0E25\u0E35\u0E49\u0E22\u0E07\u0E15\u0E48\u0E32\u0E07\u0E1B\u0E23\u0E30\u0E40\u0E17\u0E28)", required: true }
    ],
    optionalDocs: []
  },
  // ── MEALS & ENTERTAINMENT ───────────────────────────────────
  {
    level1: "Meals & Entertainment",
    level2: "Per Diem \u2014 Domestic (200/day)",
    policyRule: "Auto Approve",
    threshold: 200,
    currency: "THB",
    glCode: "5400-001",
    requiredDocs: [
      { id: "perdiem_form", label: "\u0E41\u0E1A\u0E1A\u0E1F\u0E2D\u0E23\u0E4C\u0E21\u0E40\u0E1A\u0E34\u0E01\u0E40\u0E1A\u0E35\u0E49\u0E22\u0E40\u0E25\u0E35\u0E49\u0E22\u0E07\u0E40\u0E14\u0E34\u0E19\u0E17\u0E32\u0E07", required: true },
      { id: "travel_approval", label: "\u0E2B\u0E19\u0E31\u0E07\u0E2A\u0E37\u0E2D\u0E2D\u0E19\u0E38\u0E21\u0E31\u0E15\u0E34\u0E40\u0E14\u0E34\u0E19\u0E17\u0E32\u0E07", required: true }
    ],
    optionalDocs: [
      { id: "receipt", label: "\u0E43\u0E1A\u0E40\u0E2A\u0E23\u0E47\u0E08\u0E2D\u0E32\u0E2B\u0E32\u0E23 (\u0E16\u0E49\u0E32\u0E21\u0E35)", required: false }
    ],
    notes: "\u0E40\u0E09\u0E1E\u0E32\u0E30\u0E23\u0E30\u0E14\u0E31\u0E1A\u0E15\u0E48\u0E33\u0E01\u0E27\u0E48\u0E32 Senior Manager \u0E40\u0E17\u0E48\u0E32\u0E19\u0E31\u0E49\u0E19 | \u0E40\u0E14\u0E34\u0E19\u0E17\u0E32\u0E07 \u226550 \u0E01\u0E21. \u0E02\u0E49\u0E32\u0E21\u0E08\u0E31\u0E07\u0E2B\u0E27\u0E31\u0E14 | \u0E17\u0E33\u0E07\u0E32\u0E19 \u22659 \u0E0A\u0E31\u0E48\u0E27\u0E42\u0E21\u0E07"
  },
  {
    level1: "Meals & Entertainment",
    level2: "Restaurant \u2014 Business Meal",
    policyRule: "Auto Approve",
    threshold: 3e3,
    currency: "THB",
    glCode: "5400-001",
    requiredDocs: [
      { id: "receipt", label: "\u0E43\u0E1A\u0E40\u0E2A\u0E23\u0E47\u0E08\u0E23\u0E31\u0E1A\u0E40\u0E07\u0E34\u0E19 / Receipt", required: true }
    ],
    optionalDocs: [
      { id: "tax_invoice", label: "\u0E43\u0E1A\u0E01\u0E33\u0E01\u0E31\u0E1A\u0E20\u0E32\u0E29\u0E35 (Tax Invoice)", required: false },
      { id: "business_purpose", label: "\u0E27\u0E31\u0E15\u0E16\u0E38\u0E1B\u0E23\u0E30\u0E2A\u0E07\u0E04\u0E4C\u0E17\u0E32\u0E07\u0E18\u0E38\u0E23\u0E01\u0E34\u0E08 (Business Purpose)", required: false }
    ]
  },
  {
    level1: "Meals & Entertainment",
    level2: "Night Shift Meal (60/person)",
    policyRule: "Auto Approve",
    threshold: 60,
    currency: "THB",
    glCode: "5400-002",
    requiredDocs: [
      { id: "receipt", label: "\u0E43\u0E1A\u0E40\u0E2A\u0E23\u0E47\u0E08\u0E23\u0E31\u0E1A\u0E40\u0E07\u0E34\u0E19 / Receipt", required: true },
      { id: "headcount", label: "\u0E08\u0E33\u0E19\u0E27\u0E19\u0E1E\u0E19\u0E31\u0E01\u0E07\u0E32\u0E19\u0E17\u0E35\u0E48\u0E23\u0E31\u0E1A\u0E2D\u0E32\u0E2B\u0E32\u0E23 (Head Count)", required: true },
      { id: "job_type", label: "\u0E1B\u0E23\u0E30\u0E40\u0E20\u0E17\u0E07\u0E32\u0E19 (Year-end Stock Take / Cycle Stock / Layout Remodeling / Special Project)", required: true },
      { id: "work_hours_proof", label: "\u0E2B\u0E25\u0E31\u0E01\u0E10\u0E32\u0E19\u0E01\u0E32\u0E23\u0E17\u0E33\u0E07\u0E32\u0E19 \u22658 \u0E0A\u0E31\u0E48\u0E27\u0E42\u0E21\u0E07", required: true }
    ],
    optionalDocs: [],
    notes: "\u0E1A\u0E04.67024 | \u0E21\u0E35\u0E1C\u0E25 1 \u0E21.\u0E04.\u201331 \u0E18.\u0E04. 2568 \u0E40\u0E17\u0E48\u0E32\u0E19\u0E31\u0E49\u0E19"
  },
  {
    level1: "Meals & Entertainment",
    level2: "Per Diem \u2014 Overseas",
    policyRule: "Auto Approve",
    threshold: null,
    currency: "USD",
    glCode: "5400-001",
    requiredDocs: [
      { id: "perdiem_form", label: "Per Diem Claim Form (Overseas)", required: true },
      { id: "travel_approval", label: "\u0E2B\u0E19\u0E31\u0E07\u0E2A\u0E37\u0E2D\u0E2D\u0E19\u0E38\u0E21\u0E31\u0E15\u0E34\u0E40\u0E14\u0E34\u0E19\u0E17\u0E32\u0E07\u0E15\u0E48\u0E32\u0E07\u0E1B\u0E23\u0E30\u0E40\u0E17\u0E28", required: true }
    ],
    optionalDocs: [
      { id: "receipt", label: "\u0E43\u0E1A\u0E40\u0E2A\u0E23\u0E47\u0E08\u0E2D\u0E32\u0E2B\u0E32\u0E23 (\u0E16\u0E49\u0E32\u0E21\u0E35)", required: false }
    ],
    notes: "Threshold \u0E02\u0E36\u0E49\u0E19\u0E2D\u0E22\u0E39\u0E48\u0E01\u0E31\u0E1A Employee Grade \u0E41\u0E25\u0E30 Country Group (HR-TR-002 \u0E15\u0E32\u0E23\u0E32\u0E07 2)"
  },
  {
    level1: "Meals & Entertainment",
    level2: "Client Entertainment",
    policyRule: "Requires Approval",
    threshold: null,
    currency: "THB",
    glCode: "5400-003",
    requiredDocs: [
      { id: "entertainment_form", label: "Entertainment Expense Claim Form (CA005)", required: true },
      { id: "receipt", label: "\u0E43\u0E1A\u0E40\u0E2A\u0E23\u0E47\u0E08\u0E23\u0E31\u0E1A\u0E40\u0E07\u0E34\u0E19 / Receipt", required: true },
      { id: "tax_invoice", label: "\u0E43\u0E1A\u0E01\u0E33\u0E01\u0E31\u0E1A\u0E20\u0E32\u0E29\u0E35 (Tax Invoice)", required: true },
      { id: "attendee_list", label: "\u0E23\u0E32\u0E22\u0E0A\u0E37\u0E48\u0E2D\u0E1C\u0E39\u0E49\u0E40\u0E02\u0E49\u0E32\u0E23\u0E48\u0E27\u0E21 (\u0E0A\u0E37\u0E48\u0E2D + \u0E1A\u0E23\u0E34\u0E29\u0E31\u0E17 + \u0E15\u0E33\u0E41\u0E2B\u0E19\u0E48\u0E07)", required: true },
      { id: "business_purpose", label: "\u0E27\u0E31\u0E15\u0E16\u0E38\u0E1B\u0E23\u0E30\u0E2A\u0E07\u0E04\u0E4C\u0E17\u0E32\u0E07\u0E18\u0E38\u0E23\u0E01\u0E34\u0E08 (Business Purpose)", required: true }
    ],
    optionalDocs: [
      { id: "memo", label: "Memo \u0E2D\u0E18\u0E34\u0E1A\u0E32\u0E22\u0E40\u0E2B\u0E15\u0E38\u0E1C\u0E25 (\u0E01\u0E23\u0E13\u0E35\u0E40\u0E01\u0E34\u0E19 Threshold)", required: false }
    ]
  },
  {
    level1: "Meals & Entertainment",
    level2: "Alcohol / Bar",
    policyRule: "Auto Reject",
    threshold: null,
    currency: "THB",
    glCode: null,
    requiredDocs: [],
    optionalDocs: [],
    notes: "\u0E44\u0E21\u0E48\u0E2A\u0E32\u0E21\u0E32\u0E23\u0E16\u0E40\u0E1A\u0E34\u0E01\u0E44\u0E14\u0E49\u0E17\u0E38\u0E01\u0E01\u0E23\u0E13\u0E35 \u2014 \u0E19\u0E42\u0E22\u0E1A\u0E32\u0E22\u0E1A\u0E23\u0E34\u0E29\u0E31\u0E17"
  },
  // ── ACCOMMODATION ───────────────────────────────────────────
  {
    level1: "Accommodation",
    level2: "Hotel \u2014 Domestic",
    policyRule: "Auto Approve",
    threshold: null,
    currency: "THB",
    glCode: "5200-001",
    requiredDocs: [
      { id: "hotel_folio", label: "Hotel Folio / \u0E43\u0E1A\u0E40\u0E2A\u0E23\u0E47\u0E08\u0E42\u0E23\u0E07\u0E41\u0E23\u0E21", required: true },
      { id: "tax_invoice", label: "\u0E43\u0E1A\u0E01\u0E33\u0E01\u0E31\u0E1A\u0E20\u0E32\u0E29\u0E35 (Tax Invoice)", required: true },
      { id: "travel_approval", label: "\u0E2B\u0E19\u0E31\u0E07\u0E2A\u0E37\u0E2D\u0E2D\u0E19\u0E38\u0E21\u0E31\u0E15\u0E34\u0E40\u0E14\u0E34\u0E19\u0E17\u0E32\u0E07", required: true },
      { id: "cga_booking", label: "\u0E2B\u0E25\u0E31\u0E01\u0E10\u0E32\u0E19\u0E01\u0E32\u0E23\u0E08\u0E2D\u0E07\u0E1C\u0E48\u0E32\u0E19 CGA / Agency", required: true }
    ],
    optionalDocs: [
      { id: "split_bill", label: "\u0E43\u0E1A\u0E41\u0E22\u0E01\u0E1A\u0E34\u0E25 2 \u0E43\u0E1A (\u0E01\u0E23\u0E13\u0E35\u0E1E\u0E31\u0E01\u0E40\u0E01\u0E34\u0E19\u0E27\u0E07\u0E40\u0E07\u0E34\u0E19)", required: false },
      { id: "single_room_memo", label: "\u0E2B\u0E19\u0E31\u0E07\u0E2A\u0E37\u0E2D\u0E2D\u0E18\u0E34\u0E1A\u0E32\u0E22\u0E40\u0E2B\u0E15\u0E38\u0E1C\u0E25\u0E1E\u0E31\u0E01\u0E40\u0E14\u0E35\u0E48\u0E22\u0E27 (\u0E01\u0E23\u0E13\u0E35\u0E2A\u0E34\u0E17\u0E18\u0E34\u0E4C\u0E1E\u0E31\u0E01\u0E04\u0E39\u0E48)", required: false }
    ],
    notes: "Threshold \u0E02\u0E36\u0E49\u0E19\u0E2D\u0E22\u0E39\u0E48\u0E01\u0E31\u0E1A Employee Grade (HR-TR-001 \u0E15\u0E32\u0E23\u0E32\u0E07 3)"
  },
  {
    level1: "Accommodation",
    level2: "Hotel \u2014 Overseas",
    policyRule: "Auto Approve",
    threshold: null,
    currency: "USD",
    glCode: "5200-001",
    requiredDocs: [
      { id: "hotel_folio", label: "Hotel Folio / \u0E43\u0E1A\u0E40\u0E2A\u0E23\u0E47\u0E08\u0E42\u0E23\u0E07\u0E41\u0E23\u0E21", required: true },
      { id: "tax_invoice", label: "Invoice / \u0E43\u0E1A\u0E01\u0E33\u0E01\u0E31\u0E1A\u0E20\u0E32\u0E29\u0E35", required: true },
      { id: "travel_approval", label: "\u0E2B\u0E19\u0E31\u0E07\u0E2A\u0E37\u0E2D\u0E2D\u0E19\u0E38\u0E21\u0E31\u0E15\u0E34\u0E40\u0E14\u0E34\u0E19\u0E17\u0E32\u0E07\u0E15\u0E48\u0E32\u0E07\u0E1B\u0E23\u0E30\u0E40\u0E17\u0E28", required: true },
      { id: "cga_booking", label: "\u0E2B\u0E25\u0E31\u0E01\u0E10\u0E32\u0E19\u0E01\u0E32\u0E23\u0E08\u0E2D\u0E07\u0E1C\u0E48\u0E32\u0E19 Agency / CGA", required: true }
    ],
    optionalDocs: [
      { id: "booking_confirmation", label: "Booking Confirmation", required: false }
    ],
    notes: "Threshold \u0E02\u0E36\u0E49\u0E19\u0E2D\u0E22\u0E39\u0E48\u0E01\u0E31\u0E1A Employee Grade + Country Group (HR-TR-002 \u0E15\u0E32\u0E23\u0E32\u0E07 5)"
  },
  // ── OFFICE SUPPLIES ─────────────────────────────────────────
  {
    level1: "Office Supplies",
    level2: "Stationery / Printing",
    policyRule: "Auto Approve",
    threshold: 2e3,
    currency: "THB",
    glCode: "5500-001",
    requiredDocs: [
      { id: "receipt", label: "\u0E43\u0E1A\u0E40\u0E2A\u0E23\u0E47\u0E08\u0E23\u0E31\u0E1A\u0E40\u0E07\u0E34\u0E19 / Receipt (\u0E1A\u0E31\u0E07\u0E04\u0E31\u0E1A >500 THB)", required: true },
      { id: "tax_invoice", label: "\u0E43\u0E1A\u0E01\u0E33\u0E01\u0E31\u0E1A\u0E20\u0E32\u0E29\u0E35 (Tax Invoice)", required: true }
    ],
    optionalDocs: [
      { id: "nt_catalog_ref", label: "NT Catalog Reference (\u0E01\u0E23\u0E13\u0E35\u0E2A\u0E34\u0E19\u0E04\u0E49\u0E32\u0E2D\u0E22\u0E39\u0E48\u0E43\u0E19 Catalog)", required: false }
    ]
  },
  {
    level1: "Office Supplies",
    level2: "IT Equipment",
    policyRule: "Requires Approval",
    threshold: null,
    currency: "THB",
    glCode: "5500-002",
    requiredDocs: [
      { id: "receipt", label: "\u0E43\u0E1A\u0E40\u0E2A\u0E23\u0E47\u0E08\u0E23\u0E31\u0E1A\u0E40\u0E07\u0E34\u0E19 / Receipt", required: true },
      { id: "tax_invoice", label: "\u0E43\u0E1A\u0E01\u0E33\u0E01\u0E31\u0E1A\u0E20\u0E32\u0E29\u0E35 (Tax Invoice)", required: true },
      { id: "it_approval", label: "\u0E2B\u0E19\u0E31\u0E07\u0E2A\u0E37\u0E2D\u0E2D\u0E19\u0E38\u0E21\u0E31\u0E15\u0E34\u0E08\u0E32\u0E01\u0E41\u0E1C\u0E19\u0E01 IT (>2,000 THB)", required: true },
      { id: "pr", label: "Purchase Requisition (PR)", required: true }
    ],
    optionalDocs: []
  },
  // ── OTHER ───────────────────────────────────────────────────
  {
    level1: "Other",
    level2: "Medical / OPD",
    policyRule: "Auto Approve",
    threshold: 2e3,
    currency: "THB",
    glCode: "5600-001",
    requiredDocs: [
      { id: "hospital_receipt", label: "\u0E43\u0E1A\u0E40\u0E2A\u0E23\u0E47\u0E08\u0E42\u0E23\u0E07\u0E1E\u0E22\u0E32\u0E1A\u0E32\u0E25 / \u0E04\u0E25\u0E34\u0E19\u0E34\u0E01", required: true },
      { id: "medical_cert", label: "\u0E43\u0E1A\u0E23\u0E31\u0E1A\u0E23\u0E2D\u0E07\u0E41\u0E1E\u0E17\u0E22\u0E4C", required: true }
    ],
    optionalDocs: [
      { id: "insurance_claim", label: "\u0E2B\u0E25\u0E31\u0E01\u0E10\u0E32\u0E19\u0E08\u0E32\u0E01\u0E1A\u0E23\u0E34\u0E29\u0E31\u0E17\u0E1B\u0E23\u0E30\u0E01\u0E31\u0E19 (\u0E01\u0E23\u0E13\u0E35\u0E40\u0E1A\u0E34\u0E01\u0E08\u0E32\u0E01\u0E1B\u0E23\u0E30\u0E01\u0E31\u0E19\u0E01\u0E48\u0E2D\u0E19)", required: false },
      { id: "lab_result", label: "\u0E1C\u0E25\u0E41\u0E25\u0E47\u0E1A / \u0E43\u0E1A\u0E2A\u0E23\u0E38\u0E1B\u0E15\u0E23\u0E27\u0E08\u0E2A\u0E38\u0E02\u0E20\u0E32\u0E1E", required: false }
    ]
  },
  {
    level1: "Other",
    level2: "Funeral \u2014 Wreath (\u0E1E\u0E27\u0E07\u0E2B\u0E23\u0E35\u0E14)",
    policyRule: "Auto Approve",
    threshold: 2e3,
    currency: "THB",
    glCode: "5600-004",
    requiredDocs: [
      { id: "death_cert", label: "\u0E43\u0E1A\u0E21\u0E23\u0E13\u0E30\u0E1A\u0E31\u0E15\u0E23", required: true },
      { id: "welfare_form", label: "\u0E41\u0E1A\u0E1A\u0E1F\u0E2D\u0E23\u0E4C\u0E21\u0E02\u0E2D\u0E23\u0E31\u0E1A\u0E2A\u0E27\u0E31\u0E2A\u0E14\u0E34\u0E01\u0E32\u0E23", required: true },
      { id: "wreath_receipt", label: "\u0E43\u0E1A\u0E40\u0E2A\u0E23\u0E47\u0E08\u0E04\u0E48\u0E32\u0E1E\u0E27\u0E07\u0E2B\u0E23\u0E35\u0E14\u0E08\u0E23\u0E34\u0E07 (\u22642,000 THB)", required: true }
    ],
    optionalDocs: [
      { id: "marriage_cert", label: "\u0E2A\u0E33\u0E40\u0E19\u0E32\u0E17\u0E30\u0E40\u0E1A\u0E35\u0E22\u0E19\u0E2A\u0E21\u0E23\u0E2A (\u0E01\u0E23\u0E13\u0E35\u0E04\u0E39\u0E48\u0E2A\u0E21\u0E23\u0E2A\u0E40\u0E2A\u0E35\u0E22\u0E0A\u0E35\u0E27\u0E34\u0E15)", required: false },
      { id: "birth_cert", label: "\u0E2A\u0E33\u0E40\u0E19\u0E32\u0E2A\u0E39\u0E15\u0E34\u0E1A\u0E31\u0E15\u0E23\u0E02\u0E2D\u0E07\u0E1A\u0E38\u0E15\u0E23 (\u0E01\u0E23\u0E13\u0E35\u0E1A\u0E38\u0E15\u0E23\u0E40\u0E2A\u0E35\u0E22\u0E0A\u0E35\u0E27\u0E34\u0E15)", required: false }
    ],
    notes: "HR-TR-013 | \u0E08\u0E48\u0E32\u0E22\u0E1C\u0E48\u0E32\u0E19 Petty Cash \u0E2A\u0E48\u0E27\u0E19\u0E40\u0E07\u0E34\u0E19\u0E0A\u0E48\u0E27\u0E22\u0E04\u0E48\u0E32\u0E17\u0E33\u0E28\u0E1E 10,000 THB \u0E1C\u0E48\u0E32\u0E19 Payroll"
  },
  {
    level1: "Other",
    level2: "Government License / Permit",
    policyRule: "Auto Approve",
    threshold: 3e3,
    currency: "THB",
    glCode: "5600-005",
    requiredDocs: [
      { id: "gov_receipt", label: "\u0E43\u0E1A\u0E40\u0E2A\u0E23\u0E47\u0E08\u0E08\u0E32\u0E01\u0E2B\u0E19\u0E48\u0E27\u0E22\u0E07\u0E32\u0E19\u0E23\u0E32\u0E0A\u0E01\u0E32\u0E23", required: true },
      { id: "license_copy", label: "\u0E43\u0E1A\u0E2D\u0E19\u0E38\u0E0D\u0E32\u0E15\u0E09\u0E1A\u0E31\u0E1A\u0E43\u0E2B\u0E21\u0E48 / \u0E43\u0E1A\u0E15\u0E48\u0E2D\u0E2D\u0E32\u0E22\u0E38", required: true }
    ],
    optionalDocs: []
  },
  {
    level1: "Other",
    level2: "Community / Cultural",
    policyRule: "Auto Approve",
    threshold: 1e3,
    currency: "THB",
    glCode: "5600-006",
    requiredDocs: [
      { id: "receipt", label: "\u0E43\u0E1A\u0E40\u0E2A\u0E23\u0E47\u0E08\u0E23\u0E31\u0E1A\u0E40\u0E07\u0E34\u0E19 / \u0E2B\u0E25\u0E31\u0E01\u0E10\u0E32\u0E19\u0E01\u0E32\u0E23\u0E0A\u0E33\u0E23\u0E30", required: true },
      { id: "activity_memo", label: "\u0E1A\u0E31\u0E19\u0E17\u0E36\u0E01\u0E2D\u0E18\u0E34\u0E1A\u0E32\u0E22\u0E01\u0E34\u0E08\u0E01\u0E23\u0E23\u0E21\u0E41\u0E25\u0E30\u0E04\u0E27\u0E32\u0E21\u0E40\u0E0A\u0E37\u0E48\u0E2D\u0E21\u0E42\u0E22\u0E07\u0E01\u0E31\u0E1A\u0E0A\u0E38\u0E21\u0E0A\u0E19", required: true },
      { id: "sgm_approval", label: "\u0E2D\u0E19\u0E38\u0E21\u0E31\u0E15\u0E34\u0E08\u0E32\u0E01 SGM / Store Manager", required: true }
    ],
    optionalDocs: []
  },
  {
    level1: "Other",
    level2: "Wet Waste Disposal",
    policyRule: "Auto Approve",
    threshold: 1e3,
    currency: "THB",
    glCode: "5600-007",
    requiredDocs: [
      { id: "receipt", label: "\u0E43\u0E1A\u0E40\u0E2A\u0E23\u0E47\u0E08\u0E08\u0E32\u0E01\u0E1C\u0E39\u0E49\u0E43\u0E2B\u0E49\u0E1A\u0E23\u0E34\u0E01\u0E32\u0E23\u0E01\u0E33\u0E08\u0E31\u0E14\u0E02\u0E22\u0E30", required: true },
      { id: "urgent_memo", label: "\u0E1A\u0E31\u0E19\u0E17\u0E36\u0E01\u0E2D\u0E18\u0E34\u0E1A\u0E32\u0E22\u0E40\u0E2B\u0E15\u0E38\u0E1C\u0E25\u0E17\u0E35\u0E48\u0E44\u0E21\u0E48\u0E2A\u0E32\u0E21\u0E32\u0E23\u0E16\u0E23\u0E2D Direct Payment", required: true }
    ],
    optionalDocs: []
  },
  {
    level1: "Other",
    level2: "Damaged Claims \u2014 Customer",
    policyRule: "Auto Approve",
    threshold: 500,
    currency: "THB",
    glCode: "5600-008",
    requiredDocs: [
      { id: "receipt", label: "\u0E43\u0E1A\u0E40\u0E2A\u0E23\u0E47\u0E08 / \u0E2B\u0E25\u0E31\u0E01\u0E10\u0E32\u0E19\u0E01\u0E32\u0E23\u0E0A\u0E14\u0E40\u0E0A\u0E22", required: true },
      { id: "incident_report", label: "\u0E1A\u0E31\u0E19\u0E17\u0E36\u0E01\u0E40\u0E2B\u0E15\u0E38\u0E01\u0E32\u0E23\u0E13\u0E4C (Incident Report)", required: true }
    ],
    optionalDocs: []
  },
  {
    level1: "Other",
    level2: "Cash Advance / ATM",
    policyRule: "Auto Reject",
    threshold: null,
    currency: "THB",
    glCode: null,
    requiredDocs: [],
    optionalDocs: [],
    notes: "\u0E2B\u0E49\u0E32\u0E21\u0E40\u0E1A\u0E34\u0E01\u0E40\u0E07\u0E34\u0E19\u0E2A\u0E14\u0E1C\u0E48\u0E32\u0E19\u0E1A\u0E31\u0E15\u0E23 \u2014 LOA FW-FN-001"
  },
  {
    level1: "Other",
    level2: "Personal Expense",
    policyRule: "Auto Reject",
    threshold: null,
    currency: "THB",
    glCode: null,
    requiredDocs: [],
    optionalDocs: [],
    notes: "\u0E04\u0E48\u0E32\u0E43\u0E0A\u0E49\u0E08\u0E48\u0E32\u0E22\u0E2A\u0E48\u0E27\u0E19\u0E15\u0E31\u0E27\u0E44\u0E21\u0E48\u0E2A\u0E32\u0E21\u0E32\u0E23\u0E16\u0E40\u0E1A\u0E34\u0E01\u0E44\u0E14\u0E49\u0E17\u0E38\u0E01\u0E01\u0E23\u0E13\u0E35"
  }
];

// src/lib/mcp/tools/list-policies.ts
var list_policies_default = defineTool6({
  name: "list_expense_policies",
  title: "List expense policies",
  description: "List expense types with policy rule, threshold, GL code and required documents.",
  inputSchema: { query: z5.string().optional().describe("Text to match against expense type names.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }, ctx) => {
    requireAuth(ctx);
    const rows = EXPENSE_TYPE_CONFIG.filter((e) => matches([e.level1, e.level2], query));
    return jsonResult(`${rows.length} expense type(s)`, rows);
  }
});

// src/lib/mcp/index.ts
var projectRef = "zotnosehxoomqrsgeznm";
var mcp_default = defineMcp({
  name: "corporate-credit-card",
  title: "Corporate Credit Card",
  version: "0.1.0",
  instructions: "Read-only tools for the Card Expense Management app. Start with `get_app_overview` to understand modules, roles, rules and design conventions, then use the list/get tools to look up sample transactions, claims, cards and expense policies.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [app_overview_default, list_card_transactions_default, list_claims_default, get_claim_default, list_cards_default, list_policies_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.5/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
